import { describe, it, expect } from 'vitest';
import { HEROES, WEAPONS, EQUIPMENT, PASSIVES, ENEMIES, BOSSES, EVENTS } from '../src/data';
import { Run, Random, segmentDistance, PLAYER_Y } from '../src/engine';
import { freshSave, validateSave } from '../src/save';
const make=(id='knife',seed=1729)=>new Run(id,freshSave(),seed);
function simulate(r:Run,seconds:number){for(let i=0;i<seconds*60;i++)r.tick(1/60,0);}
describe('shipped content',()=>{
 it('contains the full roster with valid references and unique IDs per catalog',()=>{expect([HEROES.length,WEAPONS.length,EQUIPMENT.length,PASSIVES.length,ENEMIES.length,BOSSES.length,EVENTS.length]).toEqual([12,36,50,72,26,8,24]);for(const data of[HEROES,WEAPONS,EQUIPMENT,PASSIVES,ENEMIES,BOSSES,EVENTS])expect(new Set(data.map(d=>d.id)).size).toBe(data.length);for(const h of HEROES)expect(WEAPONS.some(w=>w.id===h.weapon)).toBe(true);expect(new Set(WEAPONS.map(w=>w.pattern)).size).toBeGreaterThanOrEqual(17);expect(new Set(ENEMIES.map(e=>e.behavior)).size).toBe(26);expect(new Set(PASSIVES.map(p=>p.tag)).size).toBe(17);});
 it('does not contain orphan effect operations or placeholder content',()=>{const hooks=['hit','crit','kill','hurt','return','second','freeze','skill'];const ops=['heal','shield','nova','chain','gold','poison','ice','fire','shot','cooldown','pull','bloodnova'];for(const item of[...HEROES,...PASSIVES,...EQUIPMENT])for(const e of item.effects){expect(hooks).toContain(e.on);expect(ops).toContain(e.op);expect(e.amount).toBeGreaterThan(0);}for(const event of EVENTS){expect(event.options.length).toBeGreaterThanOrEqual(2);for(const o of event.options)expect(o.desc.length).toBeGreaterThan(5);}});
});
describe('combat loop',()=>{
 it('clamps the player horizontally, auto-fires upwards and spawns descending enemies',()=>{const r=make();simulate(r,2);expect(r.shots.some(s=>s.vy<0)).toBe(true);expect(r.enemies.length).toBeGreaterThan(0);for(let i=0;i<100;i++)r.tick(.05,-1);expect(r.x).toBe(28);for(let i=0;i<100;i++)r.tick(.05,1);expect(r.x).toBe(692);});
 it('kills enemies, collects experience, offers exactly three choices and resumes',()=>{const r=make();const e=r.spawnEnemy(ENEMIES[0],r.x,PLAYER_Y-70);r.damageEnemy(e,999);expect(e.dead).toBe(true);expect(r.kills).toBe(1);expect(r.drops.some(d=>d.kind==='xp')).toBe(true);r.gainXp(60);r.checkPanels();expect(r.panel).toBe('level');expect(r.choices).toHaveLength(3);const before=r.time;r.tick(.05,1);expect(r.time).toBe(before);const pending=r.pendingLevels;expect(r.chooseUpgrade(0)).toBe(true);expect(r.pendingLevels).toBe(pending-1);expect(Object.keys(r.passives).length+r.weapons.reduce((n,w)=>n+w.level,0)).toBeGreaterThan(1);});
 it('dying ends simulation and restarting resets the run',()=>{const r=make();r.shield=0;r.hurt(10000);expect(r.phase).toBe('dead');const t=r.time;r.tick(.05,1);expect(r.time).toBe(t);const restart=make();expect(restart.hp).toBe(restart.stats.maxHp);expect(restart.kills).toBe(0);expect(restart.floor).toBe(1);});
 it('pause freezes timers and input; the skill respects cooldown',()=>{const r=make();expect(r.skill()).toBe(true);expect(r.skill()).toBe(false);r.pause();const x=r.x,cd=r.skillCD;simulate(r,3);expect(r.x).toBe(x);expect(r.skillCD).toBe(cd);r.pause();r.tick(.05,1);expect(r.x).toBeGreaterThan(x);});
 it('uses swept collision and handles shield penetration',()=>{expect(segmentDistance(10,20,0,20,30,20)).toBe(0);const r=make();r.releaseAll();const e=r.spawnEnemy(ENEMIES[5],r.x,500);r.launch(WEAPONS[0],1,r.x,520,-Math.PI/2);r.tick(.05,0);expect(e.hp).toBe(e.maxHp);r.launch(WEAPONS[2],1,r.x,520,-Math.PI/2);r.tick(.05,0);expect(e.hp).toBeLessThan(e.maxHp);});
 it('caps projectiles, enemies and turrets during prolonged combat',()=>{const r=make('engineer');r.stats.maxHp=100000;r.hp=100000;r.stats.projectiles=9;for(let i=0;i<2500;i++){if(r.panel==='level')r.chooseUpgrade(0);if(r.panel==='loot')r.chooseLoot(false);if(r.panel==='clear')break;r.tick(.016,Math.sin(i*.05));}expect(r.shots.length).toBeLessThanOrEqual(650);expect(r.bullets.length).toBeLessThanOrEqual(450);expect(r.turrets.length).toBeLessThanOrEqual(6);expect(r.enemies.length).toBeLessThanOrEqual(140);});
});
describe('mechanical builds',()=>{
 it('poison ticks and freeze triggers shield regeneration',()=>{const r=make('frost');r.shield=0;const e=r.spawnEnemy(ENEMIES[4],100,100);r.applyStatus(e,'ice',4);expect(e.frozen).toBeGreaterThan(0);expect(r.shield).toBe(5);r.applyStatus(e,'poison',3);const hp=e.hp;simulate(r,.6);expect(e.hp).toBeLessThan(hp);});
 it('returning weapons come back and can be caught for healing',()=>{const r=make('raven');r.hp-=10;const before=r.hp;r.releaseAll();r.fireWeapon(WEAPONS[4],1);simulate(r,6);expect(r.hp).toBeGreaterThan(before);});
 it('gold and curse builds change power as their risks change',()=>{const r=make('coin');const before=r.power();r.gold+=200;expect(r.power()).toBeGreaterThan(before);r.gold=0;expect(r.power()).toBeLessThan(before);const hex=make('hex');const power=hex.power();hex.baseCurse+=3;hex.recalculate();expect(hex.power()).toBeGreaterThan(power);});
 it('secondary damage does not create unbounded trigger loops',()=>{const r=make();r.addPassive('volatile');r.addPassive('flash');for(let i=0;i<40;i++)r.spawnEnemy(ENEMIES[0],350+(i%5)*5,250+Math.floor(i/5)*5);r.nova(360,270,200,1000);expect(r.enemies.every(e=>e.dead)).toBe(true);expect(r.kills).toBe(40);expect(r.vfx.length).toBeLessThanOrEqual(180);});
 it('all weapon configurations fire and simulate without exceptions',()=>{for(const w of WEAPONS){const r=make();r.weapons=[{id:w.id,level:5,timer:0,burst:0}];r.stats.maxHp=10000;r.hp=10000;for(let i=0;i<6;i++)r.spawnEnemy(ENEMIES[i],100+i*90,250);simulate(r,2);expect(r.shots.every(s=>Number.isFinite(s.x)&&Number.isFinite(s.y))).toBe(true);expect(r.turrets.length+r.shots.length+r.kills).toBeGreaterThan(0);}});
 it('all hero skills perform their configured action',()=>{for(const h of HEROES){const r=make(h.id);r.gold=100;r.spawnEnemy(ENEMIES[4],r.x,180);expect(r.skill()).toBe(true);expect(r.skillCD).toBe(h.cooldown);}});
});
describe('route and transactions',()=>{
 it('refuses inaccessible route nodes and enters the selected room',()=>{const r=make();r.phase='between';r.open('map');r.col=0;r.enterNode(2);expect(r.row).toBe(0);r.enterNode(1);expect(r.row).toBe(1);expect(r.room).toBe('event');});
 it('shop cannot overspend, duplicate purchases or refresh without payment',()=>{const r=make();r.phase='between';r.open('shop');r.makeShop();r.gold=0;expect(r.buy(3)).toBe(false);r.refreshShop();expect(r.refreshes).toBe(0);r.gold=200;const cost=r.shop[3].cost;expect(r.buy(3)).toBe(true);expect(r.gold).toBe(200-cost);expect(r.buy(3)).toBe(false);});
 it('shop equipment selection returns to the shop',()=>{const r=make();r.phase='between';r.open('shop');r.makeShop();r.gold=999;r.buy(0);expect(r.panel).toBe('loot');r.chooseLoot(true);expect(r.panel).toBe('shop');expect(Object.keys(r.equipment)).toHaveLength(1);});
 it('cursed equipment is tied to its slot and removed by replacement',()=>{const r=make();const gear=r.createGear(3);gear.def=EQUIPMENT.find(g=>g.cursed)!;r.equip(gear);expect(r.curse).toBe(2);const clean=r.createGear(2);clean.def={...clean.def,slot:gear.def.slot,cursed:false};r.equip(clean);expect(r.curse).toBe(0);});
 it('quality adds affixes and special effects; gear can be rejected',()=>{const r=make();const gear=r.createGear(4);expect(gear.quality).toBe(4);expect(gear.affixes).toHaveLength(3);expect(gear.effects.length).toBeGreaterThan(gear.def.effects.length);r.loot.push(gear);r.open('loot');const gold=r.gold;r.chooseLoot(false);expect(r.gold).toBe(gold+44);expect(Object.keys(r.equipment)).toHaveLength(0);});
 it('full weapon slots require explicit replacement',()=>{const r=make();r.addWeapon('spear');r.addWeapon('axe');expect(r.addWeapon('bomb')).toBe(false);expect(r.weapons).toHaveLength(3);expect(r.addWeapon('bomb',1)).toBe(true);expect(r.weapons[1].id).toBe('bomb');});
 it('blood trades reject lethal costs; boss contract raises risk',()=>{const r=make();r.phase='between';r.open('event');r.hp=10;expect(r.eventAction(EVENTS[0].options[0])).toBe(false);r.hp=100;r.eventAction(EVENTS.find(e=>e.id==='oath')!.options[0]);expect(r.strongBoss).toBe(true);expect(r.eventAction(EVENTS.find(e=>e.id==='oath')!.options[0])).toBe(false);r.startCombat('boss');expect(r.enemies[0].maxHp).toBeCloseTo(BOSSES[0].hp*1.4);});
 it('all eight bosses transition phases, execute their patterns and reward a kill',()=>{for(let floor=1;floor<=8;floor++){const r=make();r.floor=floor;r.startCombat('boss');r.open(null);const boss=r.enemies[0];boss.hp=boss.maxHp*.3;r.tick(.02,0);expect(boss.phase).toBe(floor===8?2:1);simulate(r,3);expect(r.hazards.length+r.bullets.length+r.enemies.filter(e=>e.boss<0).length).toBeGreaterThan(0);r.damageEnemy(boss,1e9);expect(r.bossKills).toBe(1);expect(r.loot.some(g=>g.quality>=2)).toBe(true);}});
 it('clearing the final floor results in victory',()=>{const r=make();r.floor=8;r.row=4;r.phase='between';r.open('clear');r.next();expect(r.phase).toBe('victory');});
});
describe('save and determinism',()=>{
 it('rejects malformed versions and clamps invalid persisted values',()=>{expect(()=>validateSave({version:9})).toThrow();const s=validateSave({version:1,essence:-42,unlocked:['fake','forge'],stats:{kills:Infinity},upgrades:{vitality:100},settings:{sound:false}});expect(s.essence).toBe(0);expect(s.stats.kills).toBe(0);expect(s.upgrades.vitality).toBe(5);expect(s.unlocked).toContain('forge');expect(s.unlocked).not.toContain('fake');expect(s.settings.sound).toBe(false);});
 it('produces reproducible randomness for regression simulation',()=>{const a=new Random(42),b=new Random(42);for(let i=0;i<100;i++)expect(a.next()).toBe(b.next());});
});
