import Phaser from 'phaser';
import { HEROES, ENEMIES, BOSSES, WEAPONS } from './data';
import { heroArt, heroIcon, HERO_ART_W, HERO_ART_H } from './portraits';
const slime=['      xxxx      ','    xxxxxxxx    ','   xxxxxxxxxx   ','  xxxxxxxxxxxx  ',' xxxxxxxxxxxxxx ',' xxxexxxxexxxxx ',' xxxxwxxwxxxxxx ','  xxxxxxxxxxxx  ','   xxxxxxxxxx   ',' xxxxxxxxxxxxxx '];
const skull=['     xxxxxx     ','   xxxxxxxxxx   ','   xxxxxxxxxx   ','   xxexxxexxx   ','    xxxwxxx     ','     xxxxx      ','  xxxcxxcxxx    ','  xx cxxc xx    ','     cccc       ','    xx  xx      ','    xx  xx      '];
const bat=[' xx          xx ',' xxxx      xxxx ',' xxxxxx  xxxxxx ','   xxxxxxxxxx   ','     xxxxxx     ','     exxxxe     ','      xxxx      ','      x  x      '];
const humanoid=['     xxxxxx     ','    xxxxxxxx    ','    xxexxexx    ','     xwwwwx     ','     xxxxxx     ','   cccccccccc   ','  ccccxxcccccc  ','  xcxxxxxxxxcx  ','   cccccccc     ','    cccccc      ','    xx  xx      ','    xx  xx      '];
const bossPixels=['      cccc      ','   cccccccccc   ',' ccccxxxxcccccc ',' cccxxxxxxxxccc ',' ccxxexxexxxxcc ',' ccxxxxxxxxxxcc ','  cxxxwwxxxccc  ','   cccccccccc   ',' cccccccccccccc ','cccccxxxxxxccccc','cccxxxxxxxxxxccc','ccccxxxxxxxxcccc','  cccccccccccc  ','   ccc    ccc   ','  cccc    cccc  ','  xxxx    xxxx  '];
const palette=(color:string)=>({x:color,c:shade(color,-32),h:color,s:'#d9bf9b',e:'#171722',w:'#f1e6bf',d:shade(color,-52),b:'#393446'});
export function shade(hex:string,amount:number){const n=parseInt(hex.slice(1),16);const c=(v:number)=>Math.max(0,Math.min(255,v+amount));return'#'+[c(n>>16),c(n>>8&255),c(n&255)].map(x=>x.toString(16).padStart(2,'0')).join('');}
function texture(scene:Phaser.Scene,key:string,pattern:string[],color:string){const g=scene.make.graphics({x:0,y:0});const p=palette(color);pattern.forEach((row,y)=>[...row].forEach((symbol,x)=>{if(symbol!==' '){g.fillStyle(Phaser.Display.Color.HexStringToColor(p[symbol as keyof typeof p]||color).color);g.fillRect(x,y,1,1);}}));g.generateTexture(key,16,16);g.destroy();}
export function makeTextures(scene:Phaser.Scene){
 for(const h of HEROES)for(let frame=0;frame<2;frame++){const g=scene.make.graphics({x:0,y:0});for(const r of heroArt(h.id,frame)){g.fillStyle(Phaser.Display.Color.HexStringToColor(r.color).color);g.fillRect(r.x,r.y,r.w,r.h);}g.generateTexture(`hero-${h.id}${frame?'-walk':''}`,HERO_ART_W,HERO_ART_H);g.destroy();}
 for(const e of ENEMIES){const shape=['walk','split','bomb','egg','tank'].includes(e.behavior)?slime:['fast','swarm'].includes(e.behavior)?bat:['ranged','snipe','revive','shield'].includes(e.behavior)?skull:humanoid;texture(scene,`enemy-${e.id}`,shape,e.color);}
 for(const b of BOSSES)texture(scene,`boss-${b.id}`,bossPixels,b.color);
 for(const w of WEAPONS){const shape=w.heavy?['       xx       ','      xxxx      ','     xxxxxx     ','    xxxxxxxx    ','     xxxxxx     ','       ww       ','       ww       ','       ww       ','       cc       ']:w.returning?['   xx      xx   ','    xx    xx    ','     xx  xx     ','      xxxx      ','       xx       ']:w.pattern==='mine'||w.explosive?['      ww        ','     xxxx       ','    xxxxxx      ','    xxxxxx      ','    xxxxxx      ','     xxxx       ']:['       x        ','       x        ','      xxx       ','      xxx       ','       w        ','       c        ','       c        '];texture(scene,`weapon-${w.id}`,shape,w.color);}
 texture(scene,'xp',['      xx        ','     xxxx       ','    xxxxxx      ','     xxxx       ','      xx        '],'#b7e987');
 texture(scene,'gold',['     xxxx       ','    xwwxxx      ','    xwxxxx      ','    xxxxxx      ','     xxxx       '],'#edcc77');
 texture(scene,'gear',['    xxxxxx      ','   xxwwxxxx     ','    xxxxxx      ','     xxxx       ','     xxxx       '],'#bf95ec');
 texture(scene,'turret',['     xx         ','     xx         ','    cccc        ','   xxxxxx       ','  xxxxxxxx      ','  xxccccxx      ',' xx      xx     '],'#88c9ba');
}
export function pixelIcon(color:string,kind='hero',size=56){if(kind==='hero')return heroIcon(HEROES.find(h=>h.color===color)?.id||'knife',size);const pattern=kind==='boss'?bossPixels:kind==='enemy'?slime:kind==='gear'?['    xx    xx    ','   xxxxxxxxxx   ','   xxwwwwwwxx   ','    xxxwwxxx    ','    xxxwwxxx    ','    xxxxxxxx    ','    xxxxxxxx    ','   xxxxxxxxxx   ','   xxxxxxxxxx   ','    xxxxxxxx    ']:kind==='weapon'?['       x        ','       x        ','      xxx       ','      xxx       ','      xxx       ','       w        ','       c        ','      ccc       ']:bat;const colors=palette(color);let paths='';pattern.forEach((row,y)=>[...row].forEach((symbol,x)=>{if(symbol!==' ')paths+=`<path fill="${colors[symbol as keyof typeof colors]||color}" d="M${x} ${y}h1v1h-1z"/>`;}));return`<svg width="${size}" height="${size}" viewBox="0 0 16 16" shape-rendering="crispEdges" aria-hidden="true">${paths}</svg>`;}
