import type { Hero, Weapon, Passive, EquipmentDef, EnemyDef, BossDef, DungeonEvent, Mods, Effect, Tag, Slot, Pattern, Behavior, EventOption } from './types';
export const TAG_NAMES:Record<Tag,string> = {crit:'暴击',speed:'攻速',pierce:'穿透',bounce:'弹射',poison:'毒',ice:'冰',fire:'火',lightning:'雷',explosion:'爆炸',heavy:'重武器',return:'回旋',turret:'炮台',blood:'残血',shield:'护盾',gold:'金币',curse:'诅咒',luck:'幸运',control:'控制',summon:'护刃'};
export const QUALITY = ['普通','精良','稀有','史诗','传说'];
export const QUALITY_COLORS = ['#a0a5b3','#a2db74','#6cbefa','#bb91fa','#ffcc71'];
export const SLOT_NAMES:Record<Slot,string> = {head:'头部',body:'护甲',boots:'足部',charm:'饰物'};
const fx = (on:Effect['on'],op:Effect['op'],amount:number,extra:Partial<Effect>={}):Effect=>({on,op,amount,...extra});
export const HEROES:Hero[] = [
 {id:'knife',name:'刃客',title:'千刃如雨',desc:'越快越强。攻速 +25%，暴击时追加飞刀。',color:'#c5ef8a',weapon:'knife',mods:{speed:.25},effects:[fx('crit','shot',.6,{cooldown:.3})],skill:'storm',skillDesc:'刃雨：连续释放五轮扇形飞刀',cooldown:14,cost:0,unlock:'初始解锁'},
 {id:'toxic',name:'药师',title:'以毒攻毒',desc:'毒伤 +50%。中毒敌人死后散播毒雾。',color:'#9ae188',weapon:'venom',mods:{statusPower:.5},effects:[fx('kill','poison',2,{condition:'poisoned',radius:100})],skill:'plague',skillDesc:'疫潮：全场叠加 4 层毒，获得护盾',cooldown:18,cost:0,unlock:'初始解锁'},
 {id:'frost',name:'霜卫',title:'冻结战线',desc:'护盾上限 +20。冻结敌人回复护盾。',color:'#91d6fa',weapon:'icicle',mods:{shieldMax:20},effects:[fx('freeze','shield',5)],skill:'blizzard',skillDesc:'暴雪：全场冻结 3 秒',cooldown:20,cost:0,unlock:'初始解锁'},
 {id:'forge',name:'铸铁',title:'一击破城',desc:'伤害 +45%，攻速 -15%。重武器命中触发震波。',color:'#ecb27b',weapon:'axe',mods:{damage:.45,speed:-.15},effects:[fx('hit','nova',.45,{condition:'heavy',cooldown:.7,radius:65})],skill:'quake',skillDesc:'地裂：摧毁敌弹，对全场造成重击',cooldown:19,cost:25,unlock:'消耗 25 余烬'},
 {id:'coin',name:'赌徒',title:'身价就是火力',desc:'每持有 100 金币伤害 +8%。开局额外 60 金。',color:'#f4d482',weapon:'coinblade',mods:{goldPower:.08,luck:.15},effects:[],skill:'jackpot',skillDesc:'掷金：花费 15 金币释放追踪金刃',cooldown:10,cost:30,unlock:'消耗 30 余烬'},
 {id:'blood',name:'血徒',title:'绝境盛放',desc:'低于 35% 血量时伤害 +80%，吸血 +3%。',color:'#f38c9c',weapon:'blooddagger',mods:{lowDamage:.8,lifeSteal:.03},effects:[],skill:'blood',skillDesc:'血祭：花费当前生命 15%，爆发并短暂无敌',cooldown:15,cost:35,unlock:'消耗 35 余烬'},
 {id:'hex',name:'咒师',title:'深渊的价码',desc:'初始 2 诅咒。每层诅咒伤害 +10%，敌人随之增强。',color:'#be99ee',weapon:'hex',mods:{cursePower:.1},effects:[fx('kill','shield',2,{condition:'cursed'})],skill:'hex',skillDesc:'禁咒：引爆全场，获得 1 层诅咒',cooldown:22,cost:40,unlock:'消耗 40 余烬'},
 {id:'bomb',name:'火花',title:'连锁反应',desc:'爆炸范围 +35%。每第五次击杀触发爆炸。',color:'#faab76',weapon:'bomb',mods:{area:.35},effects:[fx('kill','nova',1.2,{chance:.2,radius:90})],skill:'carpet',skillDesc:'焚城：在六个位置投下延迟爆炸火药',cooldown:18,cost:45,unlock:'消耗 45 余烬'},
 {id:'engineer',name:'机巧',title:'搭起防线',desc:'炮台伤害 +45%。技能部署跟随火力。',color:'#78c6bc',weapon:'sentry',mods:{turretPower:.45},effects:[],skill:'turret',skillDesc:'工事：部署 3 座炮台，持续 12 秒',cooldown:22,cost:45,unlock:'消耗 45 余烬'},
 {id:'raven',name:'渡鸦',title:'回来才算结束',desc:'回旋伤害 +60%。接住武器恢复生命。',color:'#a8a3ed',weapon:'boomerang',mods:{returnPower:.6},effects:[fx('return','heal',1,{cooldown:.4})],skill:'orbit',skillDesc:'环刃：投出 12 把穿透回旋刃',cooldown:16,cost:50,unlock:'消耗 50 余烬'},
 {id:'spark',name:'雷行',title:'链式导电',desc:'暴击率 +12%。暴击会连锁电击。',color:'#e1dd9a',weapon:'thunder',mods:{crit:.12},effects:[fx('crit','chain',.7,{radius:160,cooldown:.3})],skill:'thunder',skillDesc:'雷罚：劈击最强目标，闪电连锁全场',cooldown:16,cost:55,unlock:'消耗 55 余烬'},
 {id:'fortune',name:'寻宝者',title:'命运偏爱贪心',desc:'幸运 +50%，金币 +25%。击杀偶尔掉落额外金币。',color:'#e7c5ac',weapon:'seeker',mods:{luck:.5,goldBonus:.25},effects:[fx('kill','gold',4,{chance:.15})],skill:'fortune',skillDesc:'命运：获得金币与护盾，本房间掉落品质提高',cooldown:25,cost:60,unlock:'消耗 60 余烬'}
];
const w=(id:string,name:string,desc:string,tag:Tag,pattern:Pattern,damage:number,interval:number,speed:number,color:string,extra:Partial<Weapon>={}):Weapon=>({id,name,desc,tag,pattern,damage,interval,speed,color,...extra});
export const WEAPONS:Weapon[] = [
 w('knife','旧飞刀','直线速射；连续命中逐步增伤。','speed','single',12,.3,520,'#c7dea7',{combo:true}),
 w('kunai','三尖苦无','三路扇形，同时覆盖三条下压路线。','speed','fan',10,.55,470,'#9ccec3',{count:3}),
 w('spear','贯日长矛','穿透 4 个目标，远距离额外增伤。','pierce','single',35,1.05,600,'#dce8b5',{pierce:4,far:.5}),
 w('axe','断头飞斧','沉重旋转，范围命中；伤害高，出手慢。','heavy','scythe',46,1.25,310,'#e7a775',{heavy:true,pierce:2}),
 w('boomerang','乌木回旋镖','飞至顶部后返回；返程可再次命中。','return','return',18,.8,400,'#b5a0df',{returning:true,pierce:3}),
 w('venom','淬毒针','毒可叠加，持续侵蚀；重新命中延长毒效。','poison','single',9,.32,550,'#86d77b',{status:'poison'}),
 w('icicle','霜棘','三路霜刺命中减速，累积 4 层冻结。','ice','fan',16,.7,430,'#91d5ff',{status:'ice',count:3}),
 w('ember','炽焰匕首','点燃目标；死亡余火会传染近处敌人。','fire','single',18,.58,450,'#ef9c6e',{status:'fire'}),
 w('thunder','雷钉','命中后导电，电击临近两个敌人。','lightning','single',20,.8,620,'#efe6a3',{status:'lightning'}),
 w('bomb','黑火药','抛物式慢弹，碰撞造成大范围爆炸。','explosion','single',32,1.15,260,'#f4b16c',{explosive:90,heavy:true}),
 w('seeker','寻迹飞刃','自动转向最近敌人，擅长捕获漏网之鱼。','luck','aim',17,.6,450,'#d3b4f4',{homing:true}),
 w('blooddagger','割脉短刃','快速三连发，叠加流血持续伤害。','blood','burst',8,.75,580,'#ef91a4',{status:'bleed',count:3}),
 w('coinblade','鎏金刃','弹射两次。每持有 100 金币额外增伤 6%。','gold','ricochet',17,.68,490,'#ecd177',{bounce:2}),
 w('hex','咒骨','穿透诅咒弹；低生命目标直接处决。','curse','single',22,.85,360,'#b28bea',{pierce:1,execute:.15}),
 w('sentry','袖珍弩台','在原地留下炮台，持续射击 7 秒；最多 6 座。','turret','turret',9,3,520,'#76cbb8'),
 w('shatter','裂片刃','命中后分裂成 3 枚向上的短刃。','pierce','split',19,.85,440,'#b9d9cb',{split:3}),
 w('pinball','弹珠飞锤','锁定弹射 4 次；适合分散敌群。','bounce','ricochet',24,1,400,'#c4bedc',{bounce:4,heavy:true}),
 w('drill','螺旋钻枪','同一敌人可被多段命中，穿透整列。','pierce','drill',6,.95,240,'#becfdf',{pierce:12}),
 w('crescent','月轮','大弧线来回扫荡；双程穿透。','return','orbit',26,1.25,300,'#c1b4ef',{returning:true,pierce:5}),
 w('meteor','陨铁矛','蓄力后投出，越远威力越高，碰撞爆炸。','heavy','charge',65,2.1,700,'#edb389',{charge:true,heavy:true,far:.7,explosive:55}),
 w('scatter','碎骨散射','近身 5 路重弹，近距离伤害 +80%。','heavy','shotgun',15,.95,400,'#d4beac',{count:5,close:.8,heavy:true}),
 w('frostwheel','冰轮','返程冰刃，冻结整条路上的敌人。','ice','return',15,.85,400,'#a3d8f2',{returning:true,pierce:3,status:'ice'}),
 w('viper','蛇吻','追踪毒针，持续追击移动目标。','poison','aim',10,.5,380,'#abd883',{homing:true,status:'poison'}),
 w('firework','爆竹束','三枚扇形爆竹，每枚独立爆炸。','explosion','fan',18,1.15,360,'#f1ae81',{count:3,explosive:65}),
 w('tesla','电弧弩台','原地部署导电炮台，命中触发连锁电击。','turret','turret',12,3.5,540,'#e7df8d',{status:'lightning'}),
 w('saw','锯刃','蛇形穿透弹，叠加流血，切开整列敌人。','blood','wave',18,.7,340,'#eea3a1',{status:'bleed',pierce:4}),
 w('rain','天落苦无','从敌群上方坠落 4 枚苦无。','pierce','rain',18,1.25,480,'#c7d4eb',{count:4,pierce:1}),
 w('mine','地裂雷','在上方埋设雷区，敌人靠近才爆炸。','explosion','mine',45,1.8,0,'#edbb7b',{explosive:110,heavy:true}),
 w('cross','十字刃','双刃交错：轨迹左右交换，覆盖两翼。','speed','cross',17,.7,450,'#a5d6c4',{count:2,pierce:1}),
 w('sun','日耀枪','细长光束贯通全场，点燃沿途敌人。','fire','beam',9,1.4,850,'#f8ca83',{pierce:30,status:'fire'}),
 w('executioner','裁决斧','蓄力大斧，处决生命低于 25% 的敌人。','heavy','charge',58,1.8,460,'#cdadc5',{heavy:true,execute:.25,charge:true}),
 w('echo','回声刃','返程分裂两枚追踪短刃。','return','return',23,1,450,'#b8b6f3',{returning:true,split:2,pierce:2}),
 w('stormstar','风暴手里剑','四向扇形导电刃，穿透后连锁闪电。','lightning','fan',12,.95,500,'#d9df9b',{count:4,status:'lightning',pierce:1}),
 w('acid','腐蚀罐','范围爆炸同时施毒，擅长处理护盾敌人。','poison','single',20,1.2,290,'#a6d67f',{status:'poison',explosive:85,pierce:1}),
 w('glaive','猎魂轮','锁定追踪、返回、穿透，返程吸引拾取物。','return','aim',25,1.1,430,'#ceafe9',{homing:true,returning:true,pierce:2}),
 w('comet','彗星连弩','短暂蓄力后连射 6 枚远距增伤箭。','speed','burst',9,1.1,650,'#d1e8ad',{count:6,far:.45,charge:true})
];
const p=(id:string,name:string,desc:string,tag:Tag,mods:Mods={},effects:Effect[]=[],max=3):Passive=>({id,name,desc,tag,mods,effects,max});
export const PASSIVES:Passive[] = [
 p('keen','鹰眼','暴击率 +8%。','crit',{crit:.08}),
 p('cruel','残酷美学','暴击倍率 +40%。','crit',{critPower:.4}),
 p('critknife','趁虚而入','暴击追加一把短刃；0.35 秒冷却。','crit',{},[fx('crit','shot',.8,{cooldown:.35})]),
 p('critshield','折光','暴击获得 3 护盾；0.4 秒冷却。','crit',{},[fx('crit','shield',3,{cooldown:.4})]),
 p('haste','快手','攻速 +15%。','speed',{speed:.15}),
 p('rhythm','战斗节拍','击杀使技能冷却缩短 0.5 秒。','speed',{},[fx('kill','cooldown',.5)]),
 p('flurry','骤雨','额外投射物 +1，但伤害 -8%。','speed',{projectiles:1,damage:-.08}),
 p('nimble','踏风','移动速度 +18%，闪避率 +4%。','speed',{move:.18,dodge:.04}),
 p('puncture','开路','所有投射物穿透 +1。','pierce',{pierce:1}),
 p('sight','长线狙击','远距离命中增伤 +25%。','pierce',{farPower:.25}),
 p('fletching','碎羽','命中有 12% 概率追加短刃。','pierce',{},[fx('hit','shot',.5,{chance:.12,cooldown:.4})]),
 p('momentum','贯穿震荡','重武器命中触发小震波；0.6 秒冷却。','pierce',{},[fx('hit','nova',.4,{condition:'heavy',radius:60,cooldown:.6})]),
 p('rebound','折返角','所有投射物弹射 +1。','bounce',{bounce:1}),
 p('elastic','弹性钢','弹射 +1，投射物数量 +1，攻速 -10%。','bounce',{bounce:1,projectiles:1,speed:-.1}),
 p('static','静电碰撞','命中有 18% 概率电击临近敌人。','bounce',{},[fx('hit','chain',.6,{chance:.18,radius:130,cooldown:.4})]),
 p('ricochetcrit','折角磨刃','暴击率 +7%，穿透 +1。','bounce',{crit:.07,pierce:1}),
 p('toxicity','浓缩毒剂','异常伤害 +25%。','poison',{statusPower:.25}),
 p('contagion','尸毒','中毒敌人死亡时，对周围叠 3 层毒。','poison',{},[fx('kill','poison',3,{condition:'poisoned',radius:100})]),
 p('venomblood','以毒续命','命中中毒敌人恢复 1 生命；0.8 秒冷却。','poison',{},[fx('hit','heal',1,{condition:'poisoned',cooldown:.8})]),
 p('poisonedge','腐刃','每次命中有 20% 概率叠毒。','poison',{},[fx('hit','poison',1,{chance:.2,cooldown:.15})]),
 p('deepfreeze','极寒','异常持续时间 +35%。','ice',{duration:.35}),
 p('iceburst','碎冰','冻结时造成范围爆炸。','ice',{},[fx('freeze','nova',1.2,{radius:85,cooldown:.5})]),
 p('icearmor','霜甲','冻结敌人获得 5 护盾。','ice',{},[fx('freeze','shield',5)]),
 p('frostbite','冻伤','命中被冻结的敌人追加流血震波。','ice',{},[fx('hit','bloodnova',.7,{condition:'frozen',radius:55,cooldown:.5})]),
 p('fuel','燃料','异常伤害 +20%，爆炸范围 +15%。','fire',{statusPower:.2,area:.15}),
 p('wildfire','野火','燃烧敌人死亡后引燃周围目标。','fire',{},[fx('kill','fire',3,{condition:'burning',radius:110})]),
 p('fireknife','余烬','暴击引燃目标。','fire',{},[fx('crit','fire',2,{cooldown:.2})]),
 p('cauterize','烙印','击杀燃烧敌人回复 2 生命。','fire',{},[fx('kill','heal',2,{condition:'burning'})]),
 p('conduct','超导','命中被冻结的敌人放出连锁雷电。','lightning',{},[fx('hit','chain',.9,{condition:'frozen',radius:170,cooldown:.5})]),
 p('overload','过载','暴击连锁电击两名目标。','lightning',{},[fx('crit','chain',.75,{radius:150,cooldown:.35})]),
 p('battery','电池','每 4 秒获得 3 护盾。','lightning',{},[fx('second','shield',3,{cooldown:4})]),
 p('arcing','电场','击杀触发临近电弧；0.5 秒冷却。','lightning',{},[fx('kill','chain',.6,{radius:140,cooldown:.5})]),
 p('blast','扩爆','爆炸及机制触发范围 +25%。','explosion',{area:.25}),
 p('volatile','易爆尸体','击杀有 25% 概率造成爆炸。','explosion',{},[fx('kill','nova',1,{chance:.25,radius:85,cooldown:.2})]),
 p('powder','黑火药心','受伤向全场敌人引爆冲击波；2 秒冷却。','explosion',{},[fx('hurt','nova',2,{radius:800,cooldown:2})]),
 p('flash','闪燃','暴击造成小型爆炸。','explosion',{},[fx('crit','nova',.65,{radius:65,cooldown:.5})]),
 p('mass','铁砧','伤害 +25%，攻速 -8%。','heavy',{damage:.25,speed:-.08}),
 p('execution','处刑名单','处决生命低于 10% 的非 Boss 敌人。','heavy',{execute:.1}),
 p('impact','势不可挡','重武器命中额外叠 2 层冰；0.3 秒冷却。','heavy',{},[fx('hit','ice',2,{condition:'heavy',cooldown:.3})]),
 p('close','贴脸勇气','近距离命中增伤 +35%，护甲 +2。','heavy',{closePower:.35,armor:2}),
 p('recall','归刃','回旋伤害 +30%。','return',{returnPower:.3}),
 p('catch','接刃疗伤','接住回旋武器回复 2 生命；0.5 秒冷却。','return',{},[fx('return','heal',2,{cooldown:.5})]),
 p('returnshield','返程守护','接住回旋武器获得 4 护盾。','return',{},[fx('return','shield',4,{cooldown:.4})]),
 p('echoes','回声增幅','回旋命中追加短刃；0.6 秒冷却。','return',{},[fx('hit','shot',.7,{condition:'return',cooldown:.6})]),
 p('engineering','精密齿轮','炮台伤害 +30%。','turret',{turretPower:.3}),
 p('blueprint','模块化','炮台命中有 20% 概率叠毒。','turret',{},[fx('hit','poison',2,{condition:'turret',chance:.2,cooldown:.3})]),
 p('maintenance','维修协议','每 5 秒回复 2 生命。','turret',{},[fx('second','heal',2,{cooldown:5})]),
 p('capacitor','炮塔电容','炮台暴击时触发电弧。','turret',{crit:.04},[fx('crit','chain',.8,{condition:'turret',radius:170,cooldown:.5})]),
 p('desperate','背水','低于 35% 血量时伤害 +40%。','blood',{lowDamage:.4}),
 p('siphon','嗜血','直接伤害的 2% 转化为生命；单次上限 3。','blood',{lifeSteal:.02}),
 p('bloodrage','血怒','残血时每 2 秒追加强力飞刀。','blood',{},[fx('second','shot',1.8,{condition:'low',cooldown:2})]),
 p('revenge','复仇','受伤获得 10 护盾；3 秒冷却。','blood',{},[fx('hurt','shield',10,{cooldown:3})]),
 p('barrier','结界','护盾上限 +18。','shield',{shieldMax:18}),
 p('recharge','再充能','每 3 秒获得 3 护盾。','shield',{},[fx('second','shield',3,{cooldown:3})]),
 p('thorn','反刺','受伤时造成 100% 反击伤害。','shield',{thorns:1}),
 p('armor','石肤','护甲 +3，移动速度 -5%。','shield',{armor:3,move:-.05}),
 p('interest','利息之刃','每持有 100 金币，伤害 +6%。','gold',{goldPower:.06}),
 p('greed','贪心口袋','金币获取 +25%。','gold',{goldBonus:.25}),
 p('midas','点金','击杀有 20% 概率额外获得 5 金币。','gold',{},[fx('kill','gold',5,{chance:.2})]),
 p('insurance','富人的护甲','持有至少 150 金币时，每 3 秒获得 5 护盾。','gold',{},[fx('second','shield',5,{condition:'rich',cooldown:3})]),
 p('forbidden','禁忌知识','每层诅咒增伤 +6%。','curse',{cursePower:.06}),
 p('hexarmor','诅咒铠甲','有诅咒时击杀获得 3 护盾。','curse',{},[fx('kill','shield',3,{condition:'cursed',cooldown:.3})]),
 p('darkdeal','恶魔契约','伤害 +30%，最大生命 -15。','curse',{damage:.3,maxHp:-15}),
 p('hexburst','厄运爆发','有诅咒时暴击触发大爆炸。','curse',{},[fx('crit','nova',.9,{condition:'cursed',radius:110,cooldown:.8})]),
 p('lucky','幸运草','幸运 +20%，更容易发现高品质物品。','luck',{luck:.2}),
 p('study','博学','经验获取 +20%。','luck',{xpBonus:.2}),
 p('magnet','磁石','拾取半径 +90，移动速度 +5%。','luck',{magnet:90,move:.05}),
 p('luckycrit','幸运一击','幸运 +10%，暴击率 +5%。','luck',{luck:.1,crit:.05}),
 p('alchemy','热毒炼金','命中中毒敌人叠加燃烧。','fire',{},[fx('hit','fire',1,{condition:'poisoned',cooldown:.3})]),
 p('coldcoin','冰封金库','冻结敌人额外获得 3 金币。','gold',{},[fx('freeze','gold',3,{cooldown:.3})]),
 p('bloodcoin','血税','受伤返还 12 金币；2 秒冷却。','gold',{},[fx('hurt','gold',12,{cooldown:2})]),
 p('soulreturn','灵魂回路','接住回旋武器使技能冷却缩短 0.6 秒。','return',{},[fx('return','cooldown',.6,{cooldown:.5})])
];
const g=(id:string,name:string,slot:Slot,desc:string,tag:Tag,mods:Mods={},effects:Effect[]=[],cursed=false):EquipmentDef=>({id,name,slot,desc,tag,mods,effects,cursed});
export const EQUIPMENT:EquipmentDef[] = [
 g('scout','斥候兜帽','head','暴击 +7%，拾取半径 +35。','crit',{crit:.07,magnet:35}),
 g('crow','鸦羽面具','head','回旋伤害 +25%，接刃回复生命。','return',{returnPower:.25},[fx('return','heal',1,{cooldown:.5})]),
 g('plague','鸟嘴面罩','head','异常伤害 +25%，命中偶尔叠毒。','poison',{statusPower:.25},[fx('hit','poison',1,{chance:.15,cooldown:.3})]),
 g('crown','寒霜冠','head','冻结敌人回复护盾。','ice',{shieldMax:12},[fx('freeze','shield',5)]),
 g('emberhood','余烬兜帽','head','燃烧敌人死亡后产生爆炸。','fire',{},[fx('kill','nova',.8,{condition:'burning',radius:80})]),
 g('coil','线圈护目镜','head','暴击放电。','lightning',{crit:.04},[fx('crit','chain',.7,{radius:150,cooldown:.4})]),
 g('smith','铸铁头盔','head','护甲 +4，重武器造成冰冻积累。','heavy',{armor:4},[fx('hit','ice',1,{condition:'heavy',cooldown:.4})]),
 g('clock','发条眼镜','head','攻速 +15%，炮台伤害 +20%。','turret',{speed:.15,turretPower:.2}),
 g('halo','碎光头环','head','护盾上限 +20，暴击回复护盾。','shield',{shieldMax:20},[fx('crit','shield',2,{cooldown:.4})]),
 g('goldcrown','守财冠','head','每 100 金币增伤 +5%。','gold',{goldPower:.05}),
 g('hexmask','低语面具','head','暴击 +15%，每层诅咒额外增伤。携带 +2 诅咒。','curse',{crit:.15,cursePower:.04},[],true),
 g('luckhat','四叶草帽','head','幸运 +30%。','luck',{luck:.3}),
 g('assassin','猎手面纱','head','处决低于 12% 生命的普通敌人。','crit',{execute:.12,critPower:.2}),
 g('leather','旧皮甲','body','生命 +15，护甲 +1。','shield',{maxHp:15,armor:1}),
 g('iron','铁甲','body','护甲 +5，移动速度 -8%。','heavy',{armor:5,move:-.08}),
 g('thorns','荆棘衣','body','受到伤害时反击，并触发冲击波。','shield',{thorns:.7},[fx('hurt','nova',.8,{radius:140,cooldown:2})]),
 g('bloodcoat','血誓外套','body','残血增伤 +50%，最大生命 +10。','blood',{lowDamage:.5,maxHp:10}),
 g('soulmail','灵魂锁甲','body','击杀回复 2 护盾。','shield',{shieldMax:15},[fx('kill','shield',2,{cooldown:.2})]),
 g('frostmail','霜纹甲','body','受伤冻结周围敌人。','ice',{armor:2},[fx('hurt','ice',5,{radius:800,cooldown:3})]),
 g('firecoat','防火围裙','body','受伤引燃全场，生命 +12。','fire',{maxHp:12},[fx('hurt','fire',2,{radius:800,cooldown:3})]),
 g('labcoat','炼金外袍','body','毒敌死亡回复生命。','poison',{statusPower:.15},[fx('kill','heal',2,{condition:'poisoned'})]),
 g('enginecoat','工坊背心','body','炮台伤害 +35%，每 5 秒修复生命。','turret',{turretPower:.35},[fx('second','heal',2,{cooldown:5})]),
 g('bombvest','炸药背心','body','爆炸范围 +25%，受伤全场爆破。','explosion',{area:.25},[fx('hurt','nova',1.5,{radius:800,cooldown:3})]),
 g('greedmail','贪婪金甲','body','金币 +35%，护甲 +2；携带 +2 诅咒。','gold',{goldBonus:.35,armor:2},[],true),
 g('voidrobe','虚空长袍','body','伤害 +45%，最大生命 -20；携带 +2 诅咒。','curse',{damage:.45,maxHp:-20},[],true),
 g('mirror','镜面护甲','body','闪避 +10%，护盾上限 +25。','shield',{dodge:.1,shieldMax:25}),
 g('runner','疾行靴','boots','移动 +25%，攻速 +8%。','speed',{move:.25,speed:.08}),
 g('anchor','锚铁靴','boots','移动 -10%，伤害 +20%，护甲 +3。','heavy',{move:-.1,damage:.2,armor:3}),
 g('ghost','幽灵步','boots','闪避 +12%，穿透 +1。','pierce',{dodge:.12,pierce:1}),
 g('bloodstep','血行靴','boots','吸血 +2%，移动 +12%。','blood',{lifeSteal:.02,move:.12}),
 g('magnetboot','磁轨靴','boots','拾取半径 +130。','luck',{magnet:130}),
 g('icewalk','冰路靴','boots','每 4 秒冻结临近敌人。','ice',{move:.1},[fx('second','ice',4,{radius:220,cooldown:4})]),
 g('firewalk','火步靴','boots','每 3 秒引燃靠近底线的敌人。','fire',{move:.1},[fx('second','fire',2,{radius:200,cooldown:3})]),
 g('coilboot','跃电靴','boots','受伤电击周围敌人。','lightning',{dodge:.04},[fx('hurt','chain',1.5,{radius:350,cooldown:2})]),
 g('returnboot','归途靴','boots','接刃获得护盾，移动 +15%。','return',{move:.15},[fx('return','shield',3,{cooldown:.5})]),
 g('goldstep','金屑鞋','boots','每 6 秒产出 4 金币。','gold',{},[fx('second','gold',4,{cooldown:6})]),
 g('hexstep','夜行靴','boots','攻速 +25%，闪避 +5%；携带 +2 诅咒。','curse',{speed:.25,dodge:.05},[],true),
 g('luckstep','兔足鞋','boots','幸运 +20%，移动 +20%。','luck',{luck:.2,move:.2}),
 g('ruby','红晶坠','charm','暴击伤害 +45%。','crit',{critPower:.45}),
 g('splitgem','裂晶','charm','投射物 +1，伤害 -5%。','speed',{projectiles:1,damage:-.05}),
 g('needle','穿心徽','charm','穿透 +2。','pierce',{pierce:2}),
 g('rubber','弹性核心','charm','弹射 +2。','bounce',{bounce:2}),
 g('tooth','毒蛇牙','charm','毒伤 +30%，毒敌死亡扩散毒。','poison',{statusPower:.3},[fx('kill','poison',2,{condition:'poisoned',radius:95})]),
 g('icegem','寒晶','charm','冻结触发碎冰爆炸。','ice',{},[fx('freeze','nova',1.4,{radius:95,cooldown:.5})]),
 g('flint','火石','charm','命中有 25% 概率燃烧。','fire',{},[fx('hit','fire',1,{chance:.25,cooldown:.2})]),
 g('battery','雷瓶','charm','击杀造成连锁电击。','lightning',{},[fx('kill','chain',.8,{radius:160,cooldown:.3})]),
 g('fuse','引线','charm','爆炸 +30%，击杀偶尔引爆。','explosion',{area:.3},[fx('kill','nova',.7,{chance:.15,radius:100})]),
 g('gearheart','机械心','charm','炮台 +40%，技能冷却随击杀减少。','turret',{turretPower:.4},[fx('kill','cooldown',.4)]),
 g('vampire','血月石','charm','吸血 +4%，最大生命 -12。','blood',{lifeSteal:.04,maxHp:-12}),
 g('hexcoin','恶魔金币','charm','金币增益 +50%，每层诅咒增伤 +5%；携带 +2 诅咒。','curse',{goldBonus:.5,cursePower:.05},[],true)
];
export const AFFIXES:{name:string; mods:Mods}[] = [
 {name:'锋利',mods:{damage:.08}},{name:'轻巧',mods:{speed:.07}},{name:'精准',mods:{crit:.035}},{name:'残忍',mods:{critPower:.18}},{name:'坚韧',mods:{maxHp:8}},{name:'石纹',mods:{armor:1}},{name:'迅捷',mods:{move:.08}},{name:'幸运',mods:{luck:.1}},{name:'磁性',mods:{magnet:25}},{name:'长效',mods:{duration:.12}},{name:'扩散',mods:{area:.12}},{name:'贪婪',mods:{goldBonus:.12}},{name:'博学',mods:{xpBonus:.1}},{name:'毒性',mods:{statusPower:.12}},{name:'共振',mods:{returnPower:.15}},{name:'精密',mods:{turretPower:.15}},{name:'屏障',mods:{shieldMax:7}},{name:'背水',mods:{lowDamage:.16}}
];
const e=(id:string,name:string,behavior:Behavior,hp:number,speed:number,damage:number,xp:number,color:string,floor:number,radius:number,desc:string):EnemyDef=>({id,name,behavior,hp,speed,damage,xp,color,floor,radius,desc});
export const ENEMIES:EnemyDef[] = [
 e('slime','苔藓史莱姆','walk',29,24,8,7,'#92ad75',1,13,'缓慢直线下压。'),
 e('bat','洞穴蝠','fast',18,65,6,6,'#a395bd',1,10,'高速直线突入底线。'),
 e('rat','疯鼠','zigzag',24,40,7,7,'#b49b8c',1,10,'左右之字形推进。'),
 e('skeleton','投骨骷髅','ranged',38,18,10,10,'#d1c9ad',1,13,'停在中线，朝玩家投骨。'),
 e('brute','岩甲兽','tank',110,13,17,18,'#a19c95',1,20,'慢速高血量，物理减伤。'),
 e('guard','盾卫','shield',64,25,12,12,'#93a6b2',1,15,'护盾周期挡住普通弹，穿透弹破防。'),
 e('charger','冲锋犬','charge',42,26,12,12,'#c89483',2,13,'停顿锁定，再冲向底线。'),
 e('splitter','裂生泥','split',70,22,11,14,'#96bfa1',2,16,'死亡分裂成三个小史莱姆。'),
 e('bombbug','火药虫','bomb',25,50,18,12,'#d6a076',2,12,'靠近玩家自爆并释放危险弹。'),
 e('necromancer','唤骨师','summon',76,13,12,20,'#b5a0d3',2,16,'每数秒召唤骷髅。'),
 e('medic','菌医','heal',50,16,8,15,'#9ccc96',3,14,'治疗周围敌人，优先击杀。'),
 e('shade','暗影刺客','stealth',40,38,12,14,'#9b91ba',3,12,'周期隐形，靠近底部现身。'),
 e('revenant','复生尸','revive',70,20,13,19,'#aaa683',3,15,'第一次死亡原地复活一半血量。'),
 e('banner','战旗仆从','aura',65,18,9,18,'#cb8c9d',3,14,'近处敌人移动加速。'),
 e('crystal','棱晶兽','resist',85,24,13,20,'#a8cae2',4,17,'异常抗性高，适合直接伤害。'),
 e('blink','闪烁魔','teleport',52,28,11,17,'#bf9fd6',4,12,'瞬移换道，并向下推进。'),
 e('leech','吸血蛭','leech',64,35,14,18,'#c18595',4,13,'命中玩家后为全场敌人回血。'),
 e('sapper','地雷工','mine',65,18,13,20,'#c1ac80',4,14,'在底线生成延迟爆炸雷区。'),
 e('magus','牵引术士','pull',72,16,12,20,'#a5a8d5',5,16,'周期强行牵引玩家横移。'),
 e('sniper','狙击骷髅','snipe',60,15,22,24,'#c9c7ba',5,14,'红线预警后沿锁定路径狙击。'),
 e('berserker','狂战魔','rage',105,25,18,24,'#d69588',5,18,'半血后移动与攻势大幅提升。'),
 e('mirrorling','镜甲虫','reflect',80,22,15,23,'#a7c4d4',6,16,'非穿透命中偶尔反射敌弹。'),
 e('swarm','群集蜂','swarm',20,49,7,9,'#d6c28b',6,9,'成群出现，挤压活动空间。'),
 e('egg','孵化囊','egg',90,10,8,18,'#b49dba',6,17,'长时间未击杀会孵化高速小怪。'),
 e('warden','结界使','ward',85,20,13,23,'#94cbbf',7,16,'为周围敌人添加一次性护盾。'),
 e('duelist','瞬斩者','dash',75,30,20,25,'#c4a2af',7,14,'横向跳跃后猛冲，威胁底线。')
];
export const ENEMY_AFFIXES = ['迅捷','铁壁','富饶','狂暴','再生','霜息','燃烧','吸血'];
export const BOSSES:BossDef[] = [
 {id:'jailer',name:'锈锁典狱长',subtitle:'第一层 · 苔痕牢狱',desc:'召唤盾卫期间铁锁护体。扇形骨弹与锁定地裂交替；半血加速。',color:'#c4b69c',hp:1400,phases:['铁锁护体 / 先清盾卫','断锁暴走 / 双重骨雨'],reward:'贯穿震荡'},
 {id:'brood',name:'百目孵母',subtitle:'第二层 · 腐沼巢穴',desc:'孵化囊会生出蜂群；优先摧毁卵。半血后毒弹封路。',color:'#abbd80',hp:2100,phases:['孵育 / 摧毁虫卵','暴育 / 毒潮封路'],reward:'尸毒'},
 {id:'golem',name:'熔核巨像',subtitle:'第三层 · 熔铁工坊',desc:'重拳锁定底线，裂隙爆破有预警。半血后连续锻打。',color:'#d6a07a',hp:2900,phases:['锻锤 / 避开裂隙','熔芯 / 连环砸击'],reward:'铁砧'},
 {id:'queen',name:'白霜女王',subtitle:'第四层 · 凝霜圣所',desc:'冰墙封路，交叉冰弹限制走位。半血后两侧同时发射。',color:'#a7d7ee',hp:3900,phases:['冰棘 / 交叉弹幕','白夜 / 冰墙压迫'],reward:'碎冰'},
 {id:'merchant',name:'黄金债主',subtitle:'第五层 · 贪婪金库',desc:'金刃呈环形落下。金钱仆从治疗它；半血后利息弹幕密集。',color:'#e1c782',hp:5100,phases:['放债 / 清理仆从','追债 / 利息翻倍'],reward:'利息之刃'},
 {id:'clock',name:'倒转钟灵',subtitle:'第六层 · 遗忘钟塔',desc:'周期倒转敌弹方向，再重新压下；半血后复制过去的射击。',color:'#b7aed9',hp:6500,phases:['钟摆 / 倒流弹幕','回响 / 双重时间'],reward:'灵魂回路'},
 {id:'hexlord',name:'七誓咒主',subtitle:'第七层 · 禁语回廊',desc:'轮流开启召唤、隐身与爆破仪式；半血后同时执行两种仪式。',color:'#c296d1',hp:8200,phases:['七誓 / 单仪式','破誓 / 双重仪式'],reward:'禁忌知识'},
 {id:'abyss',name:'深渊之心',subtitle:'第八层 · 世界裂口',desc:'三阶段最终战：心脉弹幕、召唤守门者、底线交替坍塌。',color:'#ec91a7',hp:11000,phases:['心脉 / 螺旋脉冲','撕裂 / 守门者降临','归零 / 避开坍塌'],reward:'命运终章'}
];
export const REGIONS = ['苔痕牢狱','腐沼巢穴','熔铁工坊','凝霜圣所','贪婪金库','遗忘钟塔','禁语回廊','世界裂口'];
const o=(label:string,desc:string,op:EventOption['op'],amount:number,extra:Partial<EventOption>={}):EventOption=>({label,desc,op,amount,...extra});
const ev=(id:string,name:string,text:string,options:EventOption[]):DungeonEvent=>({id,name,text,options});
export const EVENTS:DungeonEvent[] = [
 ev('bloodsmith','血铸铁砧','锻匠没有抬头。它只问你：愿意用多少血，换一次机会？',[o('献出鲜血','失去 20 生命，获得稀有以上装备。','gear',2,{blood:20}),o('付钱铸造','支付 65 金币，获得随机装备。','gear',1,{cost:65})]),
 ev('well','井中的硬币','井底的光像金币，也像某种眼睛。',[o('投币祈愿','支付 30 金币，随机获得被动。','passive',1,{cost:30}),o('探身捞取','获得 55 金币；35% 概率损失 18 生命。','gold',55,{risk:.35})]),
 ev('bones','旅人的白骨','骨架的背包完整，手仍抓着一把武器。',[o('取走武器','获得一把随机武器。','weapon',1),o('安葬旅人','恢复 22 生命。','heal',22)]),
 ev('mirror','裂开的镜子','镜中的你血流不止，但手中的刃更亮。',[o('接受倒影','伤害增加，最大生命永久减少 10。','sacrifice',10),o('打碎镜子','支付 20 金币，消除 1 诅咒。','cleanse',1,{cost:20})]),
 ev('gambler','瞎眼赌徒','他翻开三张牌。胜负已经写好，只是不知道是哪一面。',[o('小赌一把','支付 25 金币；55% 概率赢得 90 金币。','gamble',90,{cost:25}),o('押上性命','失去 12 生命，得到随机被动。','passive',1,{blood:12})]),
 ev('altar','无名神像','它的手掌朝上，另一只手指向更深处。',[o('接受赐福','获得史诗装备，增加 2 诅咒。','curse',3),o('献上金币','支付 60 金币，最大生命 +12。','hp',12,{cost:60})]),
 ev('merchant','走失的货郎','他只剩下一件好货，和半壶药。',[o('买下好货','支付 55 金币，获得稀有装备。','gear',2,{cost:55}),o('买半壶药','支付 20 金币，恢复 30 生命。','heal',30,{cost:20})]),
 ev('nest','发光的巢','巢里的东西正在呼吸。也许是幼崽，也许是宝藏。',[o('闯入巢穴','立刻挑战精英，奖励提高。','fight',1),o('拿走碎金','获得 25 金币。','gold',25)]),
 ev('library','禁书室','书页会自行翻动。每个字都像一枚针。',[o('阅读禁书','随机被动与 1 诅咒。','curse',1),o('烧掉书页','恢复 15 生命。','heal',15)]),
 ev('fountain','月光泉','清澈的水中漂着微小的冰晶。',[o('饮下泉水','恢复 35 生命。','heal',35),o('带走晶片','获得 25 护盾。','shield',25)]),
 ev('armory','封存军械库','三把刀，三种曾经的结局。',[o('拿一把刀','获得随机武器；增加 1 诅咒。','weapon',1,{risk:1}),o('拆解旧刃','获得 40 金币。','gold',40)]),
 ev('smith','沉默锻匠','他指了指你的装备，又指了指钱袋。',[o('锻造强化','支付 55 金币，随机现有装备升一品质。','upgrade',1,{cost:55}),o('换取材料','失去 8 生命，获得 40 金币。','gold',40,{blood:8})]),
 ev('thief','小偷的交易','他能弄来任何东西，但从来不保证价格。',[o('买消息','支付 25 金币，获得一枚额外重选次数。','reroll',1,{cost:25}),o('赎回宝物','支付 85 金币，获得史诗装备。','gear',3,{cost:85})]),
 ev('moth','金色飞蛾','它落在你的刀尖，翅膀上写着概率。',[o('放飞它','获得幸运草被动。','passive',2),o('跟随它','获得 50 金币；20% 概率损失 18 生命。','gold',50,{risk:.2})]),
 ev('tomb','守门者墓碑','碑文警告：力量越大，回声越响。',[o('唤醒守门者','挑战精英，获取高阶装备。','fight',2),o('献花','恢复 18 生命，消除 1 诅咒。','cleanse',2)]),
 ev('oath','深渊契约','没有署名的契约，写着你下一场 Boss 的名字。',[o('签下契约','下一个 Boss 强化 40%，掉落提高两级。','boss',1),o('付费解除','支付 35 金币，恢复 25 生命。','heal',25,{cost:35})]),
 ev('ratking','鼠王的礼物','一群鼠把你围住。它们带来了看似精致的戒指。',[o('收下戒指','获得随机装备，增加 1 诅咒。','curse',2),o('喂给它们金币','支付 20 金币，获得随机被动。','passive',1,{cost:20})]),
 ev('cocoon','玻璃茧','里面是一件与你的血液颜色相同的装备。',[o('敲开玻璃','失去 15 生命，获得稀有装备。','gear',2,{blood:15}),o('留下一枚硬币','支付 10 金币，获得 16 护盾。','shield',16,{cost:10})]),
 ev('clock','停摆的钟','指针倒转了一格。你也许能挽回一个选择。',[o('拨回指针','支付 35 金币，获得 2 次重选。','reroll',2,{cost:35}),o('取走发条','获得随机被动，失去 10 生命。','passive',1,{blood:10})]),
 ev('camp','弃置营火','一盏灯，一点温暖，和别人的足迹。',[o('休息','恢复 28 生命。','heal',28),o('搜索营地','随机普通装备和 20 金币。','gear',0)]),
 ev('tax','金币天平','天平一边是心脏，另一边是金子。',[o('贩卖生命','失去 18 生命，获得 95 金币。','gold',95,{blood:18}),o('赎回生命','支付 45 金币，最大生命 +10 并回复 10。','hp',10,{cost:45})]),
 ev('oracle','低语预言家','她说下一个房间有死亡，也有机会。',[o('听完预言','支付 30 金币，获得随机被动。','passive',1,{cost:30}),o('接受厄兆','获得 70 金币与 1 诅咒。','curse',4)]),
 ev('cleanser','除咒烛台','蜡泪落下，空气中的低语短暂消失。',[o('点亮烛火','支付 45 金币，消除 2 诅咒。','cleanse',2,{cost:45}),o('握住烛芯','失去 12 生命，消除 1 诅咒。','cleanse',1,{blood:12})]),
 ev('vault','密封宝匣','锁孔像一只闭着的眼。它在等代价。',[o('用金钥匙打开','支付 75 金币，获得传说装备。','gear',4,{cost:75}),o('用血开锁','失去 28 生命，获得史诗装备。','gear',3,{blood:28})])
];

// Expansion content uses its own trajectories and trigger operations.
WEAPONS.push(
 w('singularity','小型黑洞','缓慢飞至中场，持续吸拢附近敌人并脉冲伤害；Boss 只受伤害。','control','gravity',28,2.8,260,'#a38be8',{pierce:99}),
 w('silknet','银丝捕网','命中张开捕网，束缚周围敌人 2.5 秒，使其移速降低 65%。','control','net',18,1.1,420,'#82c9bd'),
 w('conduit','棱镜导线','悬停棱镜连接两个目标，导线同时伤害穿过连线的敌人。','lightning','tether',24,2.4,450,'#e5d991',{pierce:99}),
 w('starward','环星护刃','投出 3 枚护刃在底线上方环绕，反复伤敌并抵消接触的敌弹。','summon','satellite',16,2.2,0,'#9bcfe5',{count:3,pierce:99}),
 w('glassknife','镜像匕首','出手后延迟映出两枚斜向镜像，原刃继续向上穿透。','crit','mirror',21,.9,510,'#d0b8ef',{pierce:2}),
 w('anchor','逆流鱼叉','刺中后将普通敌人拉回上方 100 像素，鱼叉随即返程。','return','harpoon',38,1.35,520,'#9fbec8',{returning:true,heavy:true,pierce:1}),
 w('wallring','反壁飞盘','双盘沿斜线前进，碰到侧壁会反弹并增伤 12%，不锁定敌人。','bounce','discus',19,.95,420,'#ebb985',{count:2,pierce:8}),
 w('sporeseed','荆棘孢子','飞到中场扎根，周期叠毒并束缚附近敌人，持续 6 秒。','poison','seeds',18,2.6,340,'#a2cc8c',{pierce:99,status:'poison'})
);
PASSIVES.push(
 p('hexmark','破甲符','暴击标记目标，4 秒内受到的伤害增加 18%。','crit',{},[fx('crit','mark',.18,{cooldown:.4})]),
 p('backpush','稳固阵线','重武器命中将普通敌人向上击退 24 像素。','heavy',{},[fx('hit','repel',24,{condition:'heavy',cooldown:.4,radius:65})]),
 p('rootmark','青藤烙印','命中被束缚的敌人附加 20% 易伤。','control',{},[fx('hit','mark',.2,{condition:'snared',cooldown:.35})]),
 p('netshield','捕网保险','击杀被束缚的敌人恢复 4 护盾。','shield',{},[fx('kill','shield',4,{condition:'snared',cooldown:.3})]),
 p('orbitalcraft','折射操控','施放技能部署 3 枚环星护刃。','summon',{},[fx('skill','orbit',3,{cooldown:5})]),
 p('resonance','共鸣回响','技能会重放第一武器的一轮攻击。','speed',{},[fx('skill','echo',1,{cooldown:2})]),
 p('dissolution','灼毒消融','命中中毒敌人有 12% 概率消耗异常层数，造成异常爆发。','poison',{},[fx('hit','cull',1,{condition:'poisoned',chance:.12,cooldown:.6})]),
 p('markhunt','猎杀印记','被标记的敌人死亡时爆炸，伤害周围敌人。','explosion',{},[fx('kill','nova',.8,{condition:'marked',radius:110,cooldown:.5})]),
 p('clearair','净空屏障','施放技能清除敌弹与普通怪的一次性格挡。','shield',{},[fx('skill','cleanse',1,{radius:1000,cooldown:8})]),
 p('coinwall','碎金壁垒','持有至少 150 金时，受伤花费 12 金恢复 24 护盾。','gold',{},[fx('hurt','bank',12,{condition:'rich',cooldown:2})]),
 p('frosthook','霜钩回流','冻结时击退周围普通敌人 45 像素。','ice',{},[fx('freeze','repel',45,{radius:160,cooldown:.6})]),
 p('returnstars','归途群星','接住回旋武器时部署一枚环星护刃。','return',{},[fx('return','orbit',1,{cooldown:2})]),
 p('sporeweave','孢子蔓延','被束缚的敌人死亡后向周围散播 3 层毒。','poison',{},[fx('kill','poison',3,{condition:'snared',radius:140,cooldown:.4})]),
 p('suppression','压制节奏','命中被束缚的敌人使技能冷却缩短 0.4 秒。','control',{},[fx('hit','cooldown',.4,{condition:'snared',cooldown:.4})]),
 p('lastwind','逆风背水','残血受伤时，将靠近底线的普通敌人击退 100 像素。','blood',{},[fx('hurt','repel',100,{condition:'low',radius:360,cooldown:3})]),
 p('returnmark','借势回旋','回旋武器命中附加 16% 易伤。','return',{},[fx('hit','mark',.16,{condition:'return',cooldown:.4})]),
 p('towerwill','登塔意志','伤害 +4%，生命上限 +2。可持续叠加，支撑极深层构筑。','heavy',{damage:.04,maxHp:2},[],999),
 p('towerbreath','长夜呼吸','护盾上限 +3，异常伤害 +3%。可持续叠加。','shield',{shieldMax:3,statusPower:.03},[],999)
);
EVENTS.push(
 ev('weaver','银丝织者','织者愿意把敌人的脚步编进你的命运。',[o('学习织网','支付 35 金币获得随机被动。','passive',1,{cost:35}),o('收下一袋孢子','失去 15 生命，获得随机武器。','weapon',1,{blood:15}),o('拿走手工报酬','获得 30 金币。','gold',30)]),
 ev('mirrorwell','镜井','井中的你，多扔出了一把刀。',[o('借用倒影','支付 65 金币，获得随机武器。','weapon',1,{cost:65}),o('打碎镜面','获得 1 诅咒和随机被动。','curse',1),o('离开前洗伤口','回复 20 生命。','heal',20)]),
 ev('stargazer','星轨观测台','群星不再遥远，光落在你肩上。',[o('记录星图','支付 45 金币获得 2 次重选。','reroll',2,{cost:45}),o('收下星铁','失去 20 生命获得史诗装备。','gear',3,{blood:20}),o('在星光里休息','回复 25 生命。','heal',25)]),
 ev('deepdebt','深层债券','商人把利息写在一张燃烧的纸上。',[o('提前领取分红','获得 70 金币与 1 诅咒。','curse',4),o('兑付安全债券','支付 50 金币获得稀有装备。','gear',2,{cost:50}),o('抵押旧伤','生命上限 -8，伤害 +30%。','sacrifice',8)])
);
export function regionName(floor:number){return REGIONS[(Math.max(1,floor)-1)%REGIONS.length]+(floor>8?' · '+(floor<=16?'镜界':floor<=24?'终界':`深界 ${Math.ceil(floor/8)-3}`):'');}
export function bossIndex(floor:number){return (Math.max(1,floor)-1)%BOSSES.length;}
export function bossPhaseName(index:number,phase:number){return BOSSES[index].phases[phase]||'极限异变 / 交错封锁';}
