import type {Save} from './types';
import {BUILDINGS,SUPPLIES,COMMISSIONS,buildingCost,homeBonuses} from './home';
export function homeView(save:Save){const h=save.home,bonus=homeBonuses(h);return`
 <main class="full-page homestead"><div class="page-title"><div><span class="eyebrow">每次归来，让这里更好一点</span><h2>余烬家园</h2></div><button id="home-back">返回营地</button></div>
 <div class="home-resources"><span>▥ ${h.timber} 建材</span><span>✧ ${save.essence} 余烬</span><small>远征击杀与 Boss 带回建材</small></div>
 <section class="village-map" aria-label="家园建筑地图"><img src="${import.meta.env.BASE_URL}art/home-v1.png" alt="绿顶小屋、药草花园、铁匠铺、观星塔、仓库和晶石祭台组成的家园" fetchpriority="high"><div class="village-title"><strong>欢迎回家</strong><span>${BUILDINGS.reduce((n,b)=>n+(h.buildings[b.id]||0),0)} / 30 建设等级</span></div>${BUILDINGS.map(b=>`<button class="village-pin ${h.buildings[b.id]?'built':'vacant'}" data-building="${b.id}" style="left:${b.x}%;top:${b.y}%" aria-label="查看${b.name}"><span>${b.icon}</span><strong>${b.name}</strong><small>${h.buildings[b.id]?`${h.buildings[b.id]} 级`:'待建设'}</small></button>`).join('')}</section>
 <div class="home-benefits">下局加成：生命 +${bonus.mods.maxHp||0} · 初始金币 +${bonus.gold} · 重选 +${bonus.rerolls}${bonus.forged?' · 初始武器一锻':''}</div>
 <div class="home-section"><h3>建设家园</h3><span>每座建筑上限 5 级</span></div><div class="building-grid">${BUILDINGS.map(b=>{const level=h.buildings[b.id]||0,c=buildingCost(level);return`<article class="building-card"><span class="building-symbol">${b.icon}</span><div><h3>${b.name} <small>${level}/5</small></h3><p>${b.desc}</p><div class="home-pips">${'◆'.repeat(level)+'◇'.repeat(5-level)}</div><button data-build="${b.id}" ${level>=5||h.timber<c.timber||save.essence<c.essence?'disabled':''}>${level>=5?'已经满级':`${level?'升级':'建设'} · ${c.timber} 建材${c.essence?` + ${c.essence} 余烬`:''}`}</button></div></article>`;}).join('')}</div>
 <div class="home-section"><h3>出发补给</h3><span>只带一份，下一次开局消耗</span></div>${h.packed!=='none'?`<div class="packed-supply"><strong>已准备：${SUPPLIES.find(s=>s.id===h.packed)!.name}</strong><button id="unpack-supply">收回补给 · 返还建材</button></div>`:''}<div class="supply-grid">${SUPPLIES.map(s=>`<article><strong>${s.name}</strong><p>${s.desc}</p><button data-pack="${s.id}" ${h.packed!=='none'||!h.buildings[s.building]||h.timber<s.cost?'disabled':''}>${!h.buildings[s.building]?`先建设${BUILDINGS.find(b=>b.id===s.building)!.name}`:`准备 · ${s.cost} 建材`}</button></article>`).join('')}</div>
 <div class="home-section"><h3>家园委托</h3><span>永久里程碑，每项只领一次</span></div><div class="commission-list">${COMMISSIONS.map(c=>{const claimed=h.claimed.includes(c.id),progress=Math.min(c.goal,save.stats[c.stat]);return`<article><div><strong>${c.name}</strong><small>${progress}/${c.goal} · 奖励 ${c.reward} 建材</small><div class="commission-bar"><i style="width:${progress/c.goal*100}%"></i></div></div><button data-commission="${c.id}" ${claimed||progress<c.goal?'disabled':''}>${claimed?'已领取':'领取'}</button></article>`;}).join('')}</div></main>`;}
export function buildingDetail(save:Save,id:string){const b=BUILDINGS.find(b=>b.id===id)!;const level=save.home.buildings[id]||0,c=buildingCost(level);return{title:b.name,desc:`${level}/5 级 · 加成立即保存，下次远征生效。`,body:`<p>${b.desc}</p><div class="home-pips">${'◆'.repeat(level)+'◇'.repeat(5-level)}</div><div class="overlay-actions"><button class="primary" id="build-selected" ${level>=5||save.home.timber<c.timber||save.essence<c.essence?'disabled':''}>${level>=5?'已经满级':`${level?'升级':'建设'} · ${c.timber} 建材${c.essence?` + ${c.essence} 余烬`:''}`}</button></div>`};}
