import {homeView,buildingDetail} from './home-ui';
import {buildHome,packSupply,unpackSupply,claimCommission,expeditionTimber,SUPPLIES} from './home';
import {setById} from './sets';
import {setCards,setChip,setChange,setDelta,familyNote} from './set-ui';
import Phaser from 'phaser';
import { registerSW } from 'virtual:pwa-register';
import { HEROES, WEAPONS, PASSIVES, EQUIPMENT, ENEMIES, BOSSES, EVENTS, REGIONS, regionName, bossPhaseName, QUALITY, QUALITY_COLORS, SLOT_NAMES, TAG_NAMES } from './data';
import { Run, W, H } from './engine';
import { DungeonScene } from './scene';
import { pixelIcon } from './art';
import { Audio } from './audio';
import { loadSave, storeSave, validateSave } from './save';
import { bindMovementPad } from './controls';
import { MODES, BOUNTIES, TOWER_LIMIT, dailySeed } from './tower';
import { DIFFICULTY, floorValue } from './balance';
import type { Gear, Mods, Stats, Save, NodeType, EventOption, GameMode } from './types';
import './style.css';
import './mini.css';
import './expansion.css';
import './home.css';
const app=document.querySelector<HTMLDivElement>('#app')!;
let save=loadSave(),selected='knife',screen='menu',run:Run|undefined,game:Phaser.Game|undefined,scene:DungeonScene|undefined,stamp='',lastHUD=0,settled=false,resultEmbers=0,archiveTab='weapons';
let selectedMode:GameMode='tower';
const audio=new Audio();audio.enabled=save.settings.sound;
let movementPad:ReturnType<typeof bindMovementPad>|undefined,inputBlocked=false;
function resetCombatInput(){movementPad?.reset();if(scene){scene.move=0;scene.targetX=undefined;}}
const nodeLabels:Record<NodeType,string>={battle:'普通战斗',elite:'精英挑战',shop:'游商',chest:'宝箱',event:'未知事件',altar:'血色祭坛',heal:'休息营火',boss:'守层者',forge:'锻造工坊'};
const nodeIcons:Record<NodeType,string>={battle:'⚔',elite:'✦',shop:'▤',chest:'▣',event:'?',altar:'♜',heal:'✚',boss:'♛',forge:'⚒'};
const statNames:Record<keyof Stats,string>={damage:'伤害',speed:'攻速',crit:'暴击率',critPower:'暴击倍率',maxHp:'生命上限',armor:'护甲',move:'移速',luck:'幸运',magnet:'拾取半径',pierce:'穿透',bounce:'弹射',projectiles:'投射物',area:'范围',duration:'异常时长',goldBonus:'金币收益',xpBonus:'经验收益',regen:'每秒回复',dodge:'闪避率',lowDamage:'残血增伤',goldPower:'每百金增伤',cursePower:'每咒增伤',statusPower:'异常伤害',thorns:'反击倍率',lifeSteal:'吸血',execute:'处决阈值',closePower:'近距增伤',farPower:'远距增伤',shieldMax:'护盾上限',turretPower:'炮台伤害',returnPower:'回旋伤害'};
const flatStats=new Set(['maxHp','armor','magnet','pierce','bounce','projectiles','regen','shieldMax']);
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function persist(){if(!storeSave(save))toast('存储空间不足，请在设置中导出存档。');}
let toastTimer:number;function toast(text:string){const el=document.querySelector('#toast')!;el.textContent=text;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=window.setTimeout(()=>el.classList.remove('visible'),2800);}
const click=(id:string,fn:()=>void)=>document.getElementById(id)?.addEventListener('click',()=>{audio.unlock();fn();});
function header(inRun=false){return`<header class="topbar ${inRun?'run-header':''}"><div class="brand" id="home-brand"><span class="brand-mark">✦</span><strong>飞刀深渊</strong></div><div class="currency">${inRun?'<span class="gold" id="hud-gold">◈ 0</span><span class="purple" id="hud-curse">♜ 0</span>':`<span class="ember">✧ ${save.essence}</span>`}</div><div class="mini-capsule"><button id="nav-guide" aria-label="玩法说明">•••</button><i></i><button id="nav-settings" aria-label="${inRun?'暂停':'设置'}">${inRun?'Ⅱ':'⊙'}</button></div></header>`;}
function bindHeader(){click('nav-home',renderHome);click('nav-archive',()=>{screen='archive';renderArchive();});click('nav-workshop',()=>{screen='workshop';renderWorkshop();});click('nav-settings',()=>{if(screen==='run')run?.pause();else{screen='settings';renderSettings();}});click('nav-guide',showGuide);click('home-brand',()=>{if(screen==='run')run?.pause();else showMenu();});}
function showMenu(){screen='menu';destroyGame();run=undefined;const hero=HEROES.find(h=>h.id===selected)!;const unlocked=save.unlocked.includes(hero.id);
 app.innerHTML=header()+`<main class="menu"><div class="game-title"><span class="title-kicker">今天，也要多贪一层！</span><h1>飞刀<span>深渊</span></h1><p>左右躲一躲，飞刀扔不停</p></div><section class="character-stage"><div class="stage-cloud cloud-one"></div><div class="stage-cloud cloud-two"></div><div class="dungeon-gate"><i></i><i></i><i></i></div><div class="stage-floor"></div><span class="stage-badge"><i class="pixel-dot"></i>三章远征 · 24 层地牢</span><div class="character-shadow"></div><div class="featured-character">${pixelIcon(hero.color,'hero',150)}</div><div class="stage-name"><strong>${hero.name}</strong><span>${hero.title}</span></div><span class="stage-tag">${TAG_NAMES[WEAPONS.find(w=>w.id===hero.weapon)!.tag]}专精</span></section><div class="section-label"><h2>选择冒险者</h2><span>${save.unlocked.length}/12 已解锁 · 左右滑动</span></div><section class="hero-grid">${HEROES.map(h=>`<button class="hero-card ${h.id===selected?'selected':''} ${save.unlocked.includes(h.id)?'':'locked'}" data-hero="${h.id}" aria-label="选择${h.name}">${pixelIcon(h.color,'hero',44)}<strong>${h.name}</strong>${!save.unlocked.includes(h.id)?`<span class="lock-mark">◇ ${h.cost}</span>`:''}</button>`).join('')}</section><section class="selection"><div><span class="perk-label">角色特性</span><p>${hero.desc}</p></div><div class="skill-preview"><span class="skill-token">✦</span><p><strong>${hero.skillDesc.split('：')[0]}</strong><br>${hero.skillDesc.split('：')[1]} <span class="muted">· ${hero.cooldown}s</span></p></div></section><div class="mode-picker" role="group" aria-label="远征模式">${Object.entries(MODES).map(([id,mode])=>`<button data-mode="${id}" aria-pressed="${selectedMode===id}" class="${selectedMode===id?'selected':''}"><strong>${mode.name}</strong><small>${mode.desc}</small></button>`).join('')}</div><button class="primary start" id="start-run" ${!unlocked&&save.essence<hero.cost?'disabled':''}>${unlocked?'开始冒险':`解锁角色 · ${hero.cost} 余烬`} <span>▶</span><small>${unlocked?MODES[selectedMode].desc:'永久加入你的冒险队伍'}</small></button><div class="supply-note">${save.home.packed!=='none'?`已准备 ${SUPPLIES.find(s=>s.id===save.home.packed)!.name} · 下一局使用`:""}</div><div class="camp-note"><span>最深 ${save.stats.bestFloor} 层 · 已出发 ${save.stats.runs} 次</span><button class="ghost small" id="install-menu">安装到桌面 ↗</button></div><nav class="camp-dock" aria-label="营地导航"><button class="selected" id="camp-home"><span>⌂</span>营地</button><button id="nav-archive"><span>▤</span>图鉴</button><button id="nav-workshop"><span>⚒</span>工坊</button><button id="nav-home"><span>⌘</span>家园</button></nav></main>`;
 bindHeader();document.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(button=>button.onclick=()=>{selectedMode=button.dataset.mode as GameMode;showMenu();});document.querySelectorAll<HTMLButtonElement>('[data-hero]').forEach(btn=>btn.onclick=()=>{const scroll=document.querySelector('.hero-grid')!.scrollLeft;selected=btn.dataset.hero!;showMenu();document.querySelector('.hero-grid')!.scrollLeft=scroll;});click('start-run',()=>{if(!unlocked){save.essence-=hero.cost;save.unlocked.push(hero.id);persist();toast(`${hero.name} 已永久解锁`);showMenu();}else startRun();});click('install-menu',installApp);click('camp-home',showMenu);
}
function destroyGame(){movementPad?.dispose();movementPad=undefined;if(game){game.destroy(true);game=undefined;scene=undefined;}}
function startRun(){destroyGame();audio.unlock();settled=false;stamp='';screen='run';run=new Run(selected,save,selectedMode==='daily'?dailySeed():undefined,selectedMode);if(save.home.packed!=='none'){save.home.packed='none';persist();}run.onSound=(kind)=>audio.play(kind);const h=run.hero;
 app.innerHTML=header(true)+`<main class="game-layout"><section class="battle-column"><div class="battle-top"><span class="room" id="hud-room"></span><span id="hud-wave"></span></div><div class="arena-frame"><div id="arena"></div><div class="mini-player-hud"><div class="player-avatar">${pixelIcon(h.color,'hero',33)}</div><div class="mini-vitals"><div class="hp-label"><span id="hud-level">LV.01</span><span id="hp-value"></span></div><div class="bar health"><i id="hp-bar"></i></div><div class="bar shield"><i id="shield-bar"></i></div><span id="shield-value" class="shield-text"></span></div></div><div class="arena-label" id="arena-label">向上投掷 · 守住底线</div><div class="boss-hud" id="boss-hud" hidden></div><div id="overlay-host"></div></div><div class="bar xp xp-strip"><i id="xp-bar"></i></div><div class="run-strip"><button id="mutation-button">平静</button><button id="bounty-button">领取悬赏</button></div><div class="loadout-strip" id="weapon-list"></div><div class="combat-controls"><button class="move-button" id="move-left" data-move="-1" aria-label="向左移动">◀</button><div class="control-center"><button class="skill-btn ready" id="skill-button">${h.skillDesc.split('：')[0]}</button><button class="bag-btn" id="bag-button"><span>▣</span>背包</button></div><button class="move-button" id="move-right" data-move="1" aria-label="向右移动">▶</button></div><p class="controls-hint">左右两端移动 · 中央释放技能 · 战场可拖动</p></section><aside class="sidebar" hidden><div id="stat-damage"></div><div id="stat-speed"></div><div id="stat-crit"></div><div id="stat-armor"></div><div id="gear-list"></div><div id="build-tags"></div><div id="journal"></div></aside></main>`;
 document.getElementById('hud-wave')!.insertAdjacentHTML('afterend',`<button id="game-speed" class="game-speed" aria-label="游戏倍速">${save.settings.gameSpeed}×</button>`);
 bindHeader();click('skill-button',()=>run?.skill());click('bag-button',showBag);click('game-speed',showSpeed);click('mutation-button',showMutation);click('bounty-button',showBounty);
 scene=new DungeonScene();scene.setRun(run);scene.onSkill=()=>run?.skill();scene.onFrame=renderFrame;
 game=new Phaser.Game({type:Phaser.AUTO,parent:'arena',width:W,height:H,backgroundColor:'#242931',pixelArt:true,roundPixels:true,antialias:false,scene:[scene],scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},render:{powerPreference:'high-performance'},fps:{target:60,forceSetTimeOut:false},audio:{noAudio:true}});
 movementPad=bindMovementPad(document.querySelector<HTMLElement>('.combat-controls')!,dir=>{if(scene){scene.move=dir;if(dir)scene.targetX=undefined;}},()=>run?.phase==='combat'&&!run.panel);inputBlocked=false;
 window.scrollTo(0,0);renderHUD(true);
}
function setText(id:string,text:string){const el=document.getElementById(id);if(el)el.textContent=text;}
function setBar(id:string,value:number){const el=document.getElementById(id);if(el)el.style.width=`${Math.max(0,Math.min(100,value*100))}%`;}
function renderFrame(){if(!run||screen!=='run')return;const blocked=!!run.panel||run.phase!=='combat';if(blocked&&!inputBlocked)resetCombatInput();inputBlocked=blocked;if(run.phase==='dead'||run.phase==='victory'){settle();return;}if(performance.now()-lastHUD>100){lastHUD=performance.now();renderHUD();}const key=`${run.panel}:${run.revision}`;if(stamp!==key){stamp=key;renderOverlay();renderInventory();}}
function renderHUD(force=false){if(!run)return;const r=run;setText('hud-gold',`◈ ${r.gold}`);setText('hud-curse',`♜ ${r.curse} 诅咒`);setText('hud-level',`${String(r.level).padStart(2,'0')} 级`);setText('hud-room',`${String(r.floor).padStart(2,'0')} / ${regionName(r.floor)} · ${nodeLabels[r.room]}`);setText('hud-wave',r.phase==='combat'?r.room==='boss'?'守层者战':'下压 '+Math.max(0,Math.ceil(r.duration-r.roomTime))+'s':'房间肃清');setText('hp-value',`${Math.ceil(r.hp)} / ${r.stats.maxHp.toFixed(0)}`);setText('shield-value',`${Math.ceil(r.shield)} / ${r.stats.shieldMax.toFixed(0)}`);setBar('hp-bar',r.hp/r.stats.maxHp);setBar('shield-bar',r.shield/r.stats.shieldMax);setBar('xp-bar',r.xp/r.needXp);setText('stat-damage',`${r.power().toFixed(2)}×`);setText('stat-speed',`${r.attackSpeed.toFixed(2)}×`);setText('stat-crit',`${Math.round(r.stats.crit*100)}%`);setText('stat-armor',r.stats.armor.toFixed(0));
 const skill=document.getElementById('skill-button')!;skill.textContent=r.skillCD>0?`${r.hero.skillDesc.split('：')[0]} · ${Math.ceil(r.skillCD)}s`:`${r.hero.skillDesc.split('：')[0]} · 就绪`;skill.classList.toggle('ready',r.skillCD===0);(skill as HTMLButtonElement).disabled=r.skillCD>0||!!r.panel;
 setText('mutation-button',`✦ ${r.mutation.name}`);const bounty=BOUNTIES.find(b=>b.id===r.bounty?.id);setText('bounty-button',bounty?`${r.bounty!.claimed?'✓':Math.min(bounty.goal,r.bounty!.progress)>=bounty.goal?'领取奖励':'◇'} ${bounty.name} ${Math.min(bounty.goal,r.bounty!.progress)}/${bounty.goal}`:'◇ 接取本层悬赏');
 const bosses=r.enemies.filter(e=>e.boss>=0&&!e.dead),hud=document.getElementById('boss-hud')!;hud.hidden=!bosses.length;hud.innerHTML=bosses.map(boss=>{const b=BOSSES[boss.boss];return `<div class="boss-name">${b.name}${r.strongBoss?' · 强化':''}</div><div class="bar"><i style="background:${b.color};width:${Math.max(0,boss.hp/boss.maxHp)*100}%"></i></div><div class="boss-phase">${bossPhaseName(boss.boss,boss.phase)}</div>`;}).join('');
 if(force)renderInventory();
}
function renderInventory(){if(!run)return;const r=run;document.getElementById('weapon-list')!.innerHTML=r.weapons.map((own,i)=>{const w=WEAPONS.find(w=>w.id===own.id)!;return`<button class="gear-row" data-weapon="${i}" title="查看或舍弃武器">${pixelIcon(w.color,'weapon',28,w.id)}<div>${w.name}<small>${TAG_NAMES[w.tag]} · ${own.level}/5${own.forged?` · 锻${own.forged}`:''}${own.awakened?' · 觉醒':''}</small></div></button>`;}).join('')+Array.from({length:3-r.weapons.length},()=>'<div class="weapon-row empty">＋ 空武器槽</div>').join('');
 document.querySelectorAll<HTMLButtonElement>('[data-weapon]').forEach(b=>b.onclick=()=>showWeapon(Number(b.dataset.weapon)));
 document.getElementById('gear-list')!.innerHTML=(['head','body','boots','charm'] as const).map(slot=>{const gear=r.equipment[slot];return`<button class="gear-row" data-slot="${slot}"><span class="gear-slot">${SLOT_NAMES[slot]}</span>${gear?`${pixelIcon(QUALITY_COLORS[gear.quality],'gear',24)}<div style="color:${QUALITY_COLORS[gear.quality]}">${gear.def.name}<small>${QUALITY[gear.quality]}${gear.def.cursed?' · 诅咒':''}</small></div>`:'<span class="empty">未装备</span>'}</button>`;}).join('');document.querySelectorAll<HTMLButtonElement>('[data-slot]').forEach(b=>b.onclick=()=>{const gear=r.equipment[b.dataset.slot!];if(gear)showGear(gear);});
 const tags:Record<string,number>={};for(const[id,n]of Object.entries(r.passives)){const p=PASSIVES.find(p=>p.id===id)!;tags[p.tag]=(tags[p.tag]||0)+n;}document.getElementById('build-tags')!.innerHTML=Object.entries(tags).map(([tag,n])=>`<span>${TAG_NAMES[tag as keyof typeof TAG_NAMES]} ${n}</span>`).join('')||'<span>第一把刀，第一条路</span>';document.getElementById('journal')!.innerHTML=r.notices.slice(0,5).map(n=>`<p>· ${esc(n)}</p>`).join('')||'<p>· 下面只有更深的黑暗。</p>';
}
function overlay(title:string,subtitle:string,body:string,eyebrow='深渊远征',cls=''){return`<div class="overlay"><section class="overlay-panel ${cls}"><div class="eyebrow">${eyebrow}</div><h2>${title}</h2><p>${subtitle}</p>${body}</section></div>`;}
function renderOverlay(){if(!run)return;const r=run,host=document.getElementById('overlay-host')!;if(!r.panel){host.innerHTML='';return;}
 switch(r.panel){
  case'level':host.innerHTML=overlay(`等级 ${r.level} · 选择你的力量`,'三选一。每个选择，都会改变接下来的路。',`<div class="choice-grid">${r.choices.map((c,i)=>{const w=c.kind==='weapon'?WEAPONS.find(w=>w.id===c.id):undefined,p=c.kind==='passive'?PASSIVES.find(p=>p.id===c.id):undefined;const own=r.weapons.find(o=>o.id===c.id);return`<button class="choice" data-choice="${i}"><span class="label">${w?own?'武器强化':'新武器':'机制被动'} · ${TAG_NAMES[(w||p)!.tag]}</span>${pixelIcon(w?.color||'#b79ddc',w?'weapon':'gear',46,w?.id)}<strong>${(w||p)!.name}${own?` ${own.level} → ${own.level+1}`:''}</strong><p>${(w||p)!.desc}${w&&own?'<br>伤害提高 28%。':p?`<br>层数 ${(r.passives[p.id]||0)+1}/${p.max}`:''}</p>${run&&Object.keys(run.passives).some(id=>PASSIVES.find(p=>p.id===id)?.tag===(w||p)!.tag)?'<span class="synergy-note">与你已有构筑联动</span>':''}<span class="select-label">选择 →</span></button>`;}).join('')}</div><div class="overlay-actions"><button class="small" id="reroll" ${r.rerolls<=0?'disabled':''}>重选 · 剩余 ${r.rerolls}</button></div>`,'选择成长');document.querySelectorAll<HTMLButtonElement>('[data-choice]').forEach(b=>b.onclick=()=>{const index=Number(b.dataset.choice),c=r.choices[index];if(c.kind==='weapon'&&r.weapons.length===3&&!r.weapons.some(w=>w.id===c.id))chooseReplacement(i=>r.chooseUpgrade(index,i),WEAPONS.find(w=>w.id===c.id)!.name);else r.chooseUpgrade(index);});click('reroll',()=>r.reroll());break;
  case'loot':{const gear=r.loot[0];if(!gear){r.open(null);break;}const old=r.equipment[gear.def.slot];host.innerHTML=overlay('发现装备',`同一部位只能装备一件。拒绝可拆解为 ${8+gear.quality*9} 金币。`, `<div class="gear-compare">${gearBox(gear,'新发现')}${old?gearBox(old,'当前装备'):'<div class="gear-box"><span class="muted">当前装备</span><h3>空槽位</h3><p>这件装备可以直接穿上。</p></div>'}</div>${gearDifference(gear,old)}${setChange(r.equipment,gear)}${old?`<p class="settings-desc">更换会移除旧装备全部属性${old.def.cursed?'及其 2 层诅咒':''}。</p>`:''}<div class="overlay-actions"><button class="primary" id="take-loot">${old?'替换装备':'装备'}</button><button id="sell-loot">拆解 · ${8+gear.quality*9} 金币</button></div>`,'装备掉落');click('take-loot',()=>r.chooseLoot(true));click('sell-loot',()=>r.chooseLoot(false));break;}
  case'clear':host.innerHTML=overlay('底线守住了。',r.room==='boss'?'守层者倒下，深处的门打开了。':'下一条路，是安全休息，还是再贪一点？',`<div class="reward-strip"><div><b>${r.kills}</b><span>累计击杀</span></div><div><b>${r.level}</b><span>等级</span></div><div><b>${r.gold}</b><span>持有金币</span></div></div><div class="overlay-actions"><button class="primary" id="go-map">${r.row===4?r.floor>=TOWER_LIMIT&&r.mode!=='endless'?'带着余烬归来 →':'进入下一层 →':'选择下一条路 →'}</button></div>`,'房间肃清');click('go-map',()=>r.next());break;
  case'map':host.innerHTML=overlay(`${regionName(r.floor)} · 选择路线`,'只能前往相邻路线。精英掉落更好，商店会花掉你的火力储备。',`<div class="route-grid">${r.route.map((nodes,row)=>`<div class="route-row">${nodes.map((node,col)=>{const visited=r.visited.some(v=>v.row===row&&v.col===col),active=row===r.row+1&&Math.abs(col-r.col)<=1;return`<button class="node ${active?'active':visited?'visited':'future'}" data-node="${col}" data-row="${row}" ${active?'':'disabled'}><span class="node-icon">${visited?'✓':nodeIcons[node]}</span><span>${nodeLabels[node]}</span><span class="node-step">${row===4?'守层者':`房间 ${row+1}`}</span></button>`;}).join('')}</div>`).join('')}</div><p class="settings-desc">诅咒 ${r.curse}：敌人生命 +${Math.round(r.curse*8)}%，对你伤害 +${Math.round(r.curse*4.5)}%。</p>`,'下一条路');document.querySelectorAll<HTMLButtonElement>('[data-node]:not(:disabled)').forEach(b=>b.onclick=()=>r.enterNode(Number(b.dataset.node)));break;
  case'shop':host.innerHTML=overlay('游商 · 只收真金','花掉金币能立刻变强；留着金币，也可能就是你的构筑。',`<div class="shop-grid">${r.shop.map((item,i)=>{const def=item.kind==='gear'?item.gear!.def:item.kind==='weapon'?WEAPONS.find(w=>w.id===item.id)!:item.kind==='passive'?PASSIVES.find(p=>p.id===item.id)!:undefined;return`<div class="shop-card"><span class="eyebrow">${item.kind==='gear'?QUALITY[item.gear!.quality]:item.kind==='weapon'?'武器':item.kind==='passive'?'被动':'补给'}</span><strong>${def?.name||'半壶疗伤药'}</strong><p>${def?.desc||'恢复 35 生命。'}</p><button data-buy="${i}" ${item.sold||r.gold<item.cost?'disabled':''}>${item.sold?'已售出':`◈ ${item.cost} · 购买`}</button></div>`;}).join('')}</div><div class="overlay-actions"><button id="refresh-shop" ${r.gold<15+r.refreshes*10?'disabled':''}>刷新 · ${15+r.refreshes*10} 金币</button><button class="primary" id="leave-shop">离开商店 →</button></div>`,'游商补给');document.querySelectorAll<HTMLButtonElement>('[data-buy]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.buy),item=r.shop[i];if(item.kind==='weapon'&&r.weapons.length===3&&!r.weapons.some(w=>w.id===item.id))chooseReplacement(slot=>r.buy(i,slot),WEAPONS.find(w=>w.id===item.id)!.name);else r.buy(i);});click('refresh-shop',()=>r.refreshShop());click('leave-shop',()=>r.next());break;
  case'event':{r.eventId||=r.rng.pick(EVENTS).id;const event=EVENTS.find(e=>e.id===r.eventId)!;r.seen.add('event:'+event.id);host.innerHTML=overlay(event.name,event.text,`<div class="event-options">${event.options.map((o,i)=>`<button class="event-option" data-event="${i}" ${r.gold<(o.cost||0)||r.hp<=(o.blood||0)||(o.op==='upgrade'&&!Object.keys(r.equipment).length)?'disabled':''}><strong>${o.label}</strong><small>${o.desc}</small></button>`).join('')}</div><div class="overlay-actions"><button class="ghost" id="leave-event">不冒险，继续前行 →</button></div>`,'命运岔路');document.querySelectorAll<HTMLButtonElement>('[data-event]').forEach(b=>b.onclick=()=>{const o=event.options[Number(b.dataset.event)];if(o.op==='weapon'&&r.weapons.length===3)chooseReplacement(slot=>r.eventAction(o,slot),'未知武器');else r.eventAction(o);});click('leave-event',()=>r.next());break;}
  case'chest':host.innerHTML=overlay('一只未开启的宝箱','锁扣在微微震动。里面的东西值得你付出多少？',`<div class="event-options"><button class="event-option" id="safe-chest"><strong>普通开启</strong><small>获得至少精良品质的装备。</small></button><button class="event-option" id="cursed-chest"><strong>唤醒宝箱</strong><small>至少史诗装备，代价是增加 2 诅咒。</small></button></div><div class="overlay-actions"><button class="ghost" id="leave-chest">放弃宝箱 →</button></div>`,'宝箱抉择');click('safe-chest',()=>{r.receiveGear(r.createGear(1));r.open('loot');});click('cursed-chest',()=>{r.baseCurse+=2;r.recalculate();r.receiveGear(r.createGear(3));r.open('loot');});click('leave-chest',()=>r.next());break;
  case'altar':host.innerHTML=overlay('血色祭坛','神像不会讨价还价。它只接受确定的代价。',`<div class="event-options"><button class="event-option" id="altar-blood" ${r.hp<=20?'disabled':''}><strong>献出 20 生命</strong><small>获得稀有以上装备。</small></button><button class="event-option" id="altar-curse"><strong>拥抱低语</strong><small>随机被动，增加 1 诅咒。</small></button><button class="event-option" id="altar-clean" ${r.gold<45||r.baseCurse===0?'disabled':''}><strong>支付 45 金币</strong><small>消除 2 层祭坛 / 事件诅咒。装备诅咒须卸下装备。</small></button></div><div class="overlay-actions"><button class="ghost" id="leave-altar">离开祭坛 →</button></div>`,'血色祭坛');click('altar-blood',()=>r.eventAction({label:'',desc:'',op:'gear',amount:2,blood:20}));click('altar-curse',()=>r.eventAction({label:'',desc:'',op:'curse',amount:1}));click('altar-clean',()=>r.eventAction({label:'',desc:'',op:'cleanse',amount:2,cost:45}));click('leave-altar',()=>r.next());break;
  case'heal':host.innerHTML=overlay('余温尚在','片刻的安宁，也是一种奢侈。',`<div class="event-options"><button class="event-option" id="camp-heal"><strong>休息</strong><small>恢复 38 生命。</small></button><button class="event-option" id="camp-train"><strong>磨练体魄</strong><small>永久生命上限 +7。本次不休息。</small></button></div>`,'短暂休息');click('camp-heal',()=>{r.heal(38);r.next();});click('camp-train',()=>{r.extraMods.maxHp=(r.extraMods.maxHp||0)+7;r.recalculate();r.next();});break;
  case'bossintro':{const boss=BOSSES[r.bossId];host.innerHTML=overlay(boss.name,boss.subtitle,`<div class="text-center">${pixelIcon(boss.color,'boss',112)}<p>${boss.desc}</p>${r.strongBoss?'<p class="curse-info">契约强化：生命 +40%，攻击频率提高，奖励品质 +2。</p>':''}${r.enemies.filter(e=>e.boss>=0).length>1?`<p class="curse-info">双守层者：${r.enemies.filter(e=>e.boss>=0).map(e=>BOSSES[e.boss].name).join(' / ')}<br>击杀其中一位不会清场，必须全部击败。</p>`:''}<div class="overlay-actions"><button class="primary" id="fight-boss">迎战守层者 →</button></div></div>`,'守层者降临','boss-intro');click('fight-boss',()=>r.open(null));break;}
  case'forge':host.innerHTML=overlay('锻造工坊','金币换长线成长。每把武器最多锻造三次，满级且锻造过可觉醒。',`<div class="forge-list">${r.weapons.map((w,i)=>`<article class="forge-card"><strong>${WEAPONS.find(x=>x.id===w.id)!.name} · ${w.level} 级</strong><p>锻造 ${w.forged||0}/3 · 每次伤害 +18%，二锻后穿透 +1。${w.awakened?'已觉醒：每四轮攻击重奏一轮。':''}</p><div class="forge-actions"><button data-forge="${i}" ${r.gold<r.forgeCost(i)||(w.forged||0)>=3?'disabled':''}>${(w.forged||0)>=3?'锻造已满':`锻造 · ${r.forgeCost(i)} 金币`}</button><button data-awaken="${i}" ${r.gold<r.forgeCost(i,true)||w.level<5||!w.forged||w.awakened?'disabled':''}>${w.awakened?'已经觉醒':`觉醒 · ${r.forgeCost(i,true)} 金币`}</button></div></article>`).join('')}<h3>重铸装备 · ${65+r.floor*6} 金币</h3><p class="settings-desc">保留装备种类，重掷词条，品质不会降低。仍可比较后拆解。</p><div class="forge-actions">${Object.entries(r.equipment).map(([slot,g])=>`<button data-reforge="${slot}" ${r.gold<65+r.floor*6?'disabled':''}>${g.def.name}</button>`).join('')||'<span class="muted">尚未携带装备</span>'}</div></div><div class="overlay-actions"><button class="primary" id="leave-forge">离开工坊 →</button></div>`,'锻造与觉醒');document.querySelectorAll<HTMLButtonElement>('[data-forge]').forEach(b=>b.onclick=()=>r.forgeWeapon(Number(b.dataset.forge)));document.querySelectorAll<HTMLButtonElement>('[data-awaken]').forEach(b=>b.onclick=()=>r.forgeWeapon(Number(b.dataset.awaken),true));document.querySelectorAll<HTMLButtonElement>('[data-reforge]').forEach(b=>b.onclick=()=>r.reforgeGear(b.dataset.reforge!));click('leave-forge',()=>r.next());break;
  case'pause':host.innerHTML=overlay('喘口气。','地牢不会在你停下时前进。',`<div class="overlay-actions"><button class="primary" id="resume-run">继续下潜</button><button id="pause-settings">战斗设置</button><button class="danger" id="abandon-run">结束并结算</button></div><p class="settings-desc">当前远征不跨浏览器重启保存；解锁、图鉴、设置和统计自动存档。</p>`,'远征暂停');click('resume-run',()=>r.pause());click('pause-settings',()=>showQuickSettings());click('abandon-run',()=>modal('结束远征','当前装备和构筑会失去，已挣得的余烬会结算。','<div class="overlay-actions"><button class="danger" id="confirm-abandon">结算并返回</button><button id="cancel-abandon">继续远征</button></div>',()=>{click('confirm-abandon',()=>{closeModal();r.phase='dead';settle();});click('cancel-abandon',closeModal);}));break;
 }
}
function modsText(mods:Mods){return Object.entries(mods).map(([key,v])=>{const k=key as keyof Stats;const value=flatStats.has(k)?Math.round(v!*10)/10:Math.round(v!*100)+'%';return`<div>${statNames[k]} <span class="${v!>=0?'accent':'curse-info'}">${v!>=0?'+':''}${value}</span></div>`;}).join('');}
function gearDifference(gear:Gear,old?:Gear){const bonuses=setDelta(run?.equipment||{},gear);const keys=new Set([...Object.keys(gear.mods),...Object.keys(old?.mods||{}),...Object.keys(bonuses)]);return `<div class="gear-diff">${Array.from(keys).map(key=>{const k=key as keyof Stats,delta=(gear.mods[k]||0)-(old?.mods[k]||0)+(bonuses[k]||0);return {k,delta,weight:Math.abs(delta)*(flatStats.has(k)?1:100)};}).filter(x=>Math.abs(x.delta)>.001).sort((a,b)=>b.weight-a.weight).slice(0,6).map(({k,delta})=>`<span class="${delta>0?'gain':'loss'}">${statNames[k]} ${delta>0?'+':''}${flatStats.has(k)?Math.round(delta*10)/10:Math.round(delta*100)+'%'}</span>`).join('')||'<span>基础属性相同，比较词条与触发效果</span>'}</div>`;}
function gearBox(gear:Gear,label:string){return`<div class="gear-box" style="border-color:${QUALITY_COLORS[gear.quality]}66"><span class="eyebrow">${label} / ${SLOT_NAMES[gear.def.slot]}</span><h3 style="color:${QUALITY_COLORS[gear.quality]}">${gear.def.name} · ${QUALITY[gear.quality]}</h3><p>${gear.def.desc}</p>${setChip(gear,run?.equipment)}<div class="mods">${modsText(gear.mods)}</div><div class="affix">${gear.affixes.map(a=>'◇ '+a.name).join(' / ')||'无随机词条'}</div>${gear.quality>=3?'<p class="affix">✦ 品质特效：'+effectText(gear.effects[gear.effects.length-1])+'</p>':''}${gear.def.cursed?'<p class="curse-info">携带：+2 诅咒；卸下后解除</p>':''}</div>`;}
function effectText(e:Gear['effects'][number]){const hooks={hit:'命中',crit:'暴击',kill:'击杀',hurt:'受伤',return:'接刃',second:'周期',freeze:'冻结',skill:'技能'};const ops={heal:'回复生命',shield:'恢复护盾',nova:'范围冲击',chain:'连锁电击',gold:'获得金币',poison:'叠毒',ice:'积累冰冻',fire:'叠燃烧',shot:'追加飞刀',cooldown:'缩短技能冷却',pull:'吸引掉落',bloodnova:'血色冲击',mark:'易伤标记',repel:'击退',orbit:'护刃',echo:'攻击重放',cull:'异常消融',bank:'金币护盾',cleanse:'净空',bleed:'流血',snare:'束缚',doom:'终刻印记',overdrive:'短暂攻速提升',transmute:'毒火转化',wardburst:'消耗护盾爆发'};return`${hooks[e.on]}触发${ops[e.op]}`;}
function showMutation(){if(!run)return;modal(`第 ${run.floor} 层 · ${run.mutation.name}`,run.mutation.desc,`<div class="guide-text"><p>普通怪生命倍率 ${floorValue(DIFFICULTY.enemyHealth,run.floor).toFixed(1)}× · 本层金币倍率 ${run.mutation.gold.toFixed(2)}×</p><p>第 3 层起逐层轮换异变。第 9 层起守层者有第三阶段；第 16、24 层及无尽每 8 层出现双守层者。</p><p>${MODES[run.mode].name} · ${run.mode==='endless'?'没有层数上限':`目标 ${TOWER_LIMIT} 层`}</p></div>`);}
function showBounty(){if(!run)return;const r=run,b=BOUNTIES.find(b=>b.id===r.bounty?.id);const reward=(reward:string)=>reward==='gold'?`${60+r.floor*8} 金币`:reward==='gear'?'史诗以上装备':'2 次重选';
 modal('本层悬赏','每层只能接一项。奖励需要主动领取，进入下一层会重置。',b?`<div class="bounty-card"><h3>${b.name}</h3><p>${b.desc}</p><div class="reward-strip"><b>${Math.min(r.bounty!.progress,b.goal)} / ${b.goal}</b><span>${reward(b.reward)}</span></div><button class="primary" id="claim-bounty" ${r.bounty!.claimed||r.bounty!.progress<b.goal?'disabled':''}>${r.bounty!.claimed?'本层已领取':'领取悬赏奖励'}</button></div>`:`<div class="event-options">${BOUNTIES.map(b=>`<button class="event-option" data-bounty="${b.id}"><strong>${b.name}</strong><small>${b.desc}<br>奖励：${reward(b.reward)}</small></button>`).join('')}</div>`,()=>{document.querySelectorAll<HTMLButtonElement>('[data-bounty]').forEach(button=>button.onclick=()=>{r.takeBounty(button.dataset.bounty!);closeModal();});click('claim-bounty',()=>{closeModal();r.claimBounty();r.checkPanels();});});
}
let resumeAfterModal=false;
function modal(title:string,desc:string,body:string,bind?:()=>void){resetCombatInput();if(run?.phase==='combat'&&!run.panel){run.open('pause');resumeAfterModal=true;}document.querySelector('.modal-backdrop')?.remove();const el=document.createElement('div');el.className='modal-backdrop';el.innerHTML=`<section class="overlay-panel"><div class="eyebrow">飞刀深渊</div><h2>${title}</h2><p>${desc}</p>${body}<div class="overlay-actions"><button class="ghost small" id="modal-close">关闭</button></div></section>`;document.body.appendChild(el);click('modal-close',closeModal);bind?.();}
function closeModal(){document.querySelector('.modal-backdrop')?.remove();if(resumeAfterModal){run?.open(null);resumeAfterModal=false;}}
function chooseReplacement(action:(index:number)=>unknown,incoming:string){if(!run)return;modal('武器槽已满',`取得 ${incoming} 需要舍弃现有的一把武器。`, `<div class="replace-list">${run.weapons.map((w,i)=>`<button data-replace="${i}">${WEAPONS.find(x=>x.id===w.id)!.name}<br>LV.${w.level}</button>`).join('')}</div>`,()=>document.querySelectorAll<HTMLButtonElement>('[data-replace]').forEach(b=>b.onclick=()=>{action(Number(b.dataset.replace));closeModal();}));}
function showGear(gear:Gear){modal('装备详情','卸下诅咒装备会移除它带来的诅咒。',gearBox(gear,'当前装备')+`<div class="overlay-actions"><button id="unequip-gear">拆解装备 · ${8+gear.quality*9} 金币</button></div>`,()=>click('unequip-gear',()=>{if(!run)return;delete run.equipment[gear.def.slot];run.addGold(8+gear.quality*9);run.recalculate();run.revision++;closeModal();}));}
function showWeapon(index:number){if(!run)return;const own=run.weapons[index],w=WEAPONS.find(w=>w.id===own.id)!;modal(w.name,`LV.${own.level} / 5 · ${TAG_NAMES[w.tag]}`,`<p>${w.desc}</p><div class="mods">基础伤害 ${w.damage} · 基础间隔 ${w.interval}s<br>锻造 ${own.forged||0}/3 · ${own.awakened?'已觉醒：每四轮重奏一轮':'未觉醒'}</div><div class="overlay-actions"><button id="discard-weapon" ${run.weapons.length<=1?'disabled':''}>舍弃武器 · 15 金币</button></div>`,()=>click('discard-weapon',()=>{run!.weapons.splice(index,1);run!.addGold(15);run!.revision++;closeModal();}));}
function showBuild(){if(!run)return;modal('当前构筑','大多数被动最多三层；登塔意志与长夜呼吸可持续叠加。',`<div class="guide-text">${Object.entries(run.passives).map(([id,n])=>{const p=PASSIVES.find(p=>p.id===id)!;return`<p><strong>${p.name} ×${n} · ${TAG_NAMES[p.tag]}</strong><br>${p.desc}</p>`;}).join('')||'<p>升级后获得机制被动。</p>'}<div class="mods">${modsText(Object.fromEntries(Object.entries(run.stats).filter(([k,v])=>v!==0)) as Mods)}</div></div>`);}
function showBag(){if(!run)return;const r=run;modal('冒险背包',`伤害 ${r.power().toFixed(2)} 倍 · 暴击 ${Math.round(r.stats.crit*100)}% · 护甲 ${Math.round(r.stats.armor)}`,`<div class="bag-slots">${(['head','body','boots','charm'] as const).map(slot=>{const gear=r.equipment[slot];return`<button class="bag-slot" data-bag-slot="${slot}" ${gear?'':'disabled'}>${pixelIcon(gear?QUALITY_COLORS[gear.quality]:'#a4b3a7','gear',34)}<span class="muted">${SLOT_NAMES[slot]}</span><strong>${gear?gear.def.name:'空槽位'}</strong>${gear?`<small style="color:${QUALITY_COLORS[gear.quality]}">${QUALITY[gear.quality]}${gear.def.cursed?' · 诅咒':''}</small>`:''}</button>`;}).join('')}</div><div class="overlay-actions"><button id="bag-build" class="primary">查看被动构筑</button><button id="bag-sets" class="bag-sets-button">套装与系列</button></div><div class="guide-text"><p>携带 ${r.curse} 层诅咒 · ${r.kills} 击杀<br>点击装备查看词条，或拆解腾出槽位。</p></div>`,()=>{document.querySelectorAll<HTMLButtonElement>('[data-bag-slot]').forEach(b=>b.onclick=()=>{const gear=r.equipment[b.dataset.bagSlot!];if(gear)showGear(gear);});click('bag-build',showBuild);click('bag-sets',()=>modal('套装与系列',familyNote,setCards(r.equipment)));});}
function showGuide(){modal('守住最后一条底线','像素地牢 / 单机 / Roguelite',`<div class="guide-text"><p><strong>左右移动，自动向上投掷。</strong><br>A / D 或方向键移动；空格施放角色技能；P / Esc 暂停。手机可按方向按钮，也可以在战场拖动。</p><p><strong>敌人到底线就会伤你。</strong><br>红色投射物和预警区域也会造成伤害；拾取落下的绿色经验与金币，升级选择三选一。</p><p><strong>3 把武器，4 件装备。</strong><br>相同武器升级至 5 级，新武器满槽须替换；装备分五种品质，随机词条叠加，史诗与传说额外附带触发机制。</p><p><strong>金币和诅咒，是有代价的力量。</strong><br>金币流靠持币增伤；花掉金币意味着失去部分加成。每层诅咒让敌人生命 +8%，伤害 +4.5%；装备诅咒随卸下解除。</p><p><strong>24 层远征，无尽模式继续挑战。</strong><br>每层五个房间：选择路线、精英、商店、事件和锻造。第 16、24 层是双 Boss；第 9 层起有三阶段异变。悬赏每层可接一项，金币用于强化、觉醒或重铸。失败和胜利都带回余烬，可解锁角色与工坊成长。</p><p><strong>系列、套装与家园。</strong><br>同系列不同部位激活 2 / 3 / 4 件效果。获得装备后，同系列抽取权重稍微增加；替换装备时会显示套装得失。击杀和 Boss 结算带回建材，在营地家园建设建筑、准备下一局补给、领取委托。</p><p><strong>离线安装。</strong><br>在线打开一次完成缓存，即可安装后离线游玩。更新需主动点击，远征期间不会强制刷新。</p></div>`);}
function settle(){if(!run||settled)return;settled=true;const r=run;resultEmbers=6+r.floor*2+Math.floor(r.kills/8)+r.bossKills*12+(r.phase==='victory'?80:0);const timber=expeditionTimber(r.floor,r.kills,r.bossKills);save.home.timber=Math.min(1e9,save.home.timber+timber);save.essence+=resultEmbers;save.stats.runs++;save.stats.kills+=r.kills;save.stats.bosses+=r.bossKills;save.stats.bestFloor=Math.max(save.stats.bestFloor,r.floor);save.stats.gold+=r.totalGold;if(r.phase==='victory')save.stats.wins++;save.seen=[...new Set([...save.seen,...r.seen])];persist();screen='results';destroyGame();
 app.innerHTML=header()+`<main class="results"><span class="eyebrow">${r.phase==='victory'?'远征通关':'余烬仍在，继续出发'}</span><div>${pixelIcon(r.hero.color,'hero',94)}</div><h1>${r.phase==='victory'?'深渊，已被你洞穿。':'这一次，止步于此。'}</h1><p>${r.hero.name} · ${regionName(r.floor)} · 活过 ${Math.floor(r.time/60)} 分 ${Math.floor(r.time%60)} 秒</p><div class="result-stats"><div><strong>${r.floor}</strong><span>到达层数</span></div><div><strong>${r.kills}</strong><span>击杀</span></div><div><strong>${r.level}</strong><span>最终等级</span></div><div><strong>${r.bossKills}</strong><span>守层者</span></div></div><div class="essence-reward">✧ +${resultEmbers} 余烬 <span class="muted">/ 持有 ${save.essence}</span></div><p class="home-reward">▥ +${timber} 建材 · 已送回家园</p><p>余烬已保存。死亡带走装备，却带不走你学会的东西。</p><div class="build-tags">${r.weapons.map(w=>`<span>${WEAPONS.find(x=>x.id===w.id)!.name} LV.${w.level}</span>`).join('')}${Object.entries(r.passives).slice(0,8).map(([id,n])=>`<span>${PASSIVES.find(p=>p.id===id)!.name} ×${n}</span>`).join('')}</div><div class="overlay-actions"><button class="primary" id="again">再下一次 →</button><button id="back-menu">选择角色 / 解锁</button><button id="result-workshop">余烬工坊</button><button id="result-home">返回家园</button></div><p class="seed-info">种子 ${r.rng.state>>>0} · 远征 #${save.stats.runs}</p></main>`;bindHeader();click('again',startRun);click('back-menu',showMenu);click('result-home',renderHome);click('result-workshop',()=>{screen='workshop';renderWorkshop();});
}
function renderArchive(){const tabs=[['weapons','武器',WEAPONS],['passives','被动',PASSIVES],['equipment','装备',EQUIPMENT],['enemies','敌人',ENEMIES],['bosses','守层者',BOSSES],['events','事件',EVENTS]] as const;const current=tabs.find(t=>t[0]===archiveTab)!;
 app.innerHTML=header()+`<main class="full-page"><div class="page-title"><div><span class="eyebrow">发现与记录</span><h2>深渊图鉴</h2></div><button id="archive-back">返回营地</button></div><div class="archive-tabs">${tabs.map(([id,label,data])=>`<button data-tab="${id}" class="small ${id===archiveTab?'selected':''}">${label} ${data.length}</button>`).join('')}<button id="archive-sets" class="small">套装指南 8</button></div><div class="archive-search"><input id="archive-search" type="search" placeholder="搜索名称、效果或机制" aria-label="搜索图鉴"><span id="archive-count">${current[2].length} 项</span></div><div class="archive-grid">${current[2].map(item=>{const seen=save.seen.includes(archiveTab==='events'?'event:'+item.id:item.id),color='color'in item?item.color:'#b79cd7',desc='desc'in item?item.desc:'text'in item?item.text:'';return`<article data-search="${esc(item.name+' '+desc+('tag'in item?' '+TAG_NAMES[item.tag]:'')+('set'in item?' '+(setById(item.set)?.name||''):''))}" class="archive-card ${seen?'':'unseen'}">${pixelIcon(color,archiveTab==='weapons'?'weapon':archiveTab==='bosses'?'boss':archiveTab==='enemies'?'enemy':'gear',40,item.id)}<div><h3>${item.name} ${seen?'<span class="accent">·</span>':'<small class="muted">未发现</small>'}</h3><p>${desc}</p>${'tag'in item?`<span class="pill">${TAG_NAMES[item.tag]}</span>`:''}${'set'in item?`<span class="set-chip">${setById(item.set)?.name||''}</span>`:''}</div></article>`;}).join('')}</div></main>`;bindHeader();click('archive-back',showMenu);click('archive-sets',()=>modal('八大套装',familyNote,setCards({},true)));document.getElementById('archive-search')!.addEventListener('input',event=>{const q=(event.target as HTMLInputElement).value.trim().toLowerCase();let count=0;document.querySelectorAll<HTMLElement>('[data-search]').forEach(card=>{card.hidden=!card.dataset.search!.toLowerCase().includes(q);if(!card.hidden)count++;});setText('archive-count',`${count} 项`);});document.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(b=>b.onclick=()=>{archiveTab=b.dataset.tab!;renderArchive();});
}
function renderHome(){screen='home';app.innerHTML=header()+homeView(save);bindHeader();click('home-back',showMenu);
 const build=(id:string)=>{if(buildHome(save,id)){persist();audio.play('upgrade');renderHome();}};
 document.querySelectorAll<HTMLButtonElement>('[data-build]').forEach(b=>b.onclick=()=>build(b.dataset.build!));
 document.querySelectorAll<HTMLButtonElement>('[data-building]').forEach(b=>b.onclick=()=>{const id=b.dataset.building!,detail=buildingDetail(save,id);modal(detail.title,detail.desc,detail.body,()=>click('build-selected',()=>{closeModal();build(id);}));});
 document.querySelectorAll<HTMLButtonElement>('[data-pack]').forEach(b=>b.onclick=()=>{if(packSupply(save,b.dataset.pack!)){persist();renderHome();toast('补给已准备，将在下一次开局使用。');}});
 click('unpack-supply',()=>{if(unpackSupply(save)){persist();renderHome();}});
 document.querySelectorAll<HTMLButtonElement>('[data-commission]').forEach(b=>b.onclick=()=>{if(claimCommission(save,b.dataset.commission!)){persist();renderHome();audio.play('upgrade');}});
}
function renderWorkshop(){const items=[{id:'vitality' as const,name:'余烬体魄',desc:'每级开局生命上限 +5。上限五级。',color:'#e699a7'},{id:'fortune' as const,name:'命运微光',desc:'每级开局幸运 +3%。上限五级。',color:'#c4e58e'},{id:'supply' as const,name:'行囊补给',desc:'每级开局金币 +10。上限五级。',color:'#e8ce8e'}];
 app.innerHTML=header()+`<main class="full-page"><div class="page-title"><div><span class="eyebrow">永久成长</span><h2>余烬工坊</h2></div><button id="workshop-back">返回营地</button></div><p class="settings-desc">永远的小优势。角色解锁在营地进行；构筑仍由每一局的选择决定。</p><div class="workshop-grid" style="margin-top:24px">${items.map(item=>{const n=save.upgrades[item.id],cost=20+n*20;return`<article class="workshop-card">${pixelIcon(item.color,'gear',60)}<h3>${item.name}</h3><p>${item.desc}</p><div class="levels">${'◆'.repeat(n)+'◇'.repeat(5-n)}</div><button data-meta="${item.id}" class="primary" ${n>=5||save.essence<cost?'disabled':''}>${n>=5?'已满级':`✧ ${cost} 余烬 · 强化`}</button></article>`;}).join('')}</div><p class="settings-desc">累计 ${save.stats.runs} 次远征 · ${save.stats.kills} 击杀 · ${save.stats.bosses} 守层者 · ${save.stats.wins} 次通关。</p></main>`;bindHeader();click('workshop-back',showMenu);document.querySelectorAll<HTMLButtonElement>('[data-meta]').forEach(b=>b.onclick=()=>{const key=b.dataset.meta as keyof Save['upgrades'],n=save.upgrades[key],cost=20+n*20;if(save.essence>=cost&&n<5){save.essence-=cost;save.upgrades[key]++;persist();renderWorkshop();audio.play('upgrade');}});
}
const settingsLabels={sound:'合成音效',shake:'轻微屏幕震动',numbers:'伤害数字',particles:'像素粒子'};
function speedBody(){return `<div class="speed-options" role="group" aria-label="选择游戏倍速">${[1,2,3,4,5].map(speed=>`<button data-speed="${speed}" aria-pressed="${save.settings.gameSpeed===speed}" class="${save.settings.gameSpeed===speed?'selected':''}">${speed}×</button>`).join('')}</div>`;}
function bindSpeed(after:()=>void){document.querySelectorAll<HTMLButtonElement>('[data-speed]').forEach(button=>button.onclick=()=>{save.settings.gameSpeed=Number(button.dataset.speed) as Save['settings']['gameSpeed'];persist();setText('game-speed',`${save.settings.gameSpeed}×`);after();});}
function showSpeed(){modal('游戏倍速','加快战斗、刷怪和冷却；升级与装备选择时始终暂停。',speedBody(),()=>bindSpeed(closeModal));}
function settingsBody(){return `<div class="setting-row speed-setting"><span>游戏倍速</span>${speedBody()}</div>`+Object.entries(settingsLabels).map(([key,label])=>`<div class="setting-row"><span>${label}</span><button class="toggle ${save.settings[key as keyof typeof settingsLabels]?'on':''}" data-setting="${key}">${save.settings[key as keyof typeof settingsLabels]?'开启':'关闭'}</button></div>`).join('');}
function bindSettings(render:()=>void){bindSpeed(render);document.querySelectorAll<HTMLButtonElement>('[data-setting]').forEach(b=>b.onclick=()=>{const key=b.dataset.setting as keyof typeof settingsLabels;save.settings[key]=!save.settings[key];audio.enabled=save.settings.sound;audio.unlock();persist();render();});}
function showQuickSettings(){modal('画面与声音','设置立即生效并自动保存。',settingsBody(),()=>bindSettings(showQuickSettings));}
function renderSettings(){app.innerHTML=header()+`<main class="full-page settings"><div class="page-title"><div><span class="eyebrow">冒险营地</span><h2>设置与存档</h2></div><button id="settings-back">返回营地</button></div>${settingsBody()}<div class="setting-row"><span>存档备份</span><div><button class="small" id="export-save">导出</button> <button class="small" id="import-save">导入</button><input id="import-file" type="file" accept="application/json,.json" hidden></div></div><div class="setting-row"><span>独立应用 / 离线</span><button class="small" id="settings-install">安装应用 ↗</button></div><p class="settings-desc">存档保存在此浏览器的 localStorage。包括角色解锁、余烬、图鉴、工坊、家园、补给、设置与统计；清除浏览器数据会删除存档。换设备前请导出备份。</p><p class="settings-desc">Windows：Edge / Chrome 地址栏安装图标。Android：Chrome 菜单 → 安装应用。首次完整在线打开后可离线游玩。</p></main>`;bindHeader();click('settings-back',showMenu);bindSettings(renderSettings);click('settings-install',installApp);click('export-save',()=>{const blob=new Blob([JSON.stringify(save,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='knife-depths-save.json';a.click();URL.revokeObjectURL(url);toast('存档已导出');});click('import-save',()=>document.getElementById('import-file')!.click());document.getElementById('import-file')!.addEventListener('change',async event=>{const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return;if(file.size>1000000){toast('存档文件过大');return;}try{const next=validateSave(JSON.parse(await file.text()));modal('导入存档','将替换当前设备的解锁、余烬与统计。',`<p>${next.stats.runs} 次远征 · ${next.essence} 余烬 · ${next.unlocked.length} 角色</p><div class="overlay-actions"><button class="primary" id="confirm-import">确认导入</button></div>`,()=>click('confirm-import',()=>{save=next;audio.enabled=save.settings.sound;persist();closeModal();renderSettings();toast('存档已导入');}));}catch(error){toast(error instanceof Error?error.message:'存档无法读取');}});}
let installPrompt:{prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>}|undefined;
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event as unknown as typeof installPrompt;});
async function installApp(){if(installPrompt){await installPrompt.prompt();await installPrompt.userChoice;installPrompt=undefined;}else modal('安装飞刀深渊','独立窗口，离线下潜。',`<div class="guide-text"><p><strong>Windows</strong><br>使用 Edge 或 Chrome 打开已部署的 HTTPS 站点，点击地址栏的安装图标。</p><p><strong>Android</strong><br>使用 Chrome 打开站点，菜单 → 安装应用 / 添加到主屏幕。</p><p>先完整在线打开一次，等待缓存完成。之后可直接从桌面或主屏幕离线运行。当前浏览器若不支持安装，请用系统浏览器打开。</p></div>`);}
let updateReady=false;
const updateSW=registerSW({immediate:true,onNeedRefresh(){updateReady=true;document.getElementById('pwa-banner')!.innerHTML='新版本已准备好。结束本次远征后更新。<br><button class="small" id="update-app">立即更新</button><button class="ghost small" id="update-later">稍后</button>';click('update-app',()=>{if(screen==='run'){toast('请先结束远征，避免丢失本局构筑。');return;}void updateSW(true);});click('update-later',()=>{document.getElementById('pwa-banner')!.innerHTML='';});},onOfflineReady(){toast('离线缓存完成，可断网下潜。');},onRegisterError(error){console.warn('离线缓存注册失败',error);}});
window.addEventListener('visibilitychange',()=>{if(document.hidden&&run?.phase==='combat'&&!run.panel)run.pause();});
window.addEventListener('keydown',e=>{if(screen==='run'&&['Space','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();});
window.addEventListener('blur',resetCombatInput);
for(const event of ['contextmenu','selectstart','dragstart'])app.addEventListener(event,e=>{if((e.target as Element).closest('.game-layout'))e.preventDefault();});
window.addEventListener('beforeunload',e=>{if(screen==='run'&&run?.phase==='combat'){e.preventDefault();}});
// Expose a read-only snapshot only in development for simulation diagnostics.
if(import.meta.env.DEV)Object.defineProperty(window,'knifeDepths',{get:()=>({screen,phase:run?.phase,panel:run?.panel,enemyCount:run?.enemies.length,shotCount:run?.shots.length,hp:run?.hp,level:run?.level,updateReady})});
showMenu();
